### ISSUE TITLE
UI: Editing permissions shouldn't require `+` of an empty row to save the populated one

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1019]
1.  Edit a collection
2.  Add a group permission, say "archivists" -> "edit"
3.  Update Collection
4.  Return to edit page: interface does not show any saved permission.

### Step 2 
![screen shot 2017-05-22 at 6 17 03 pm](https://cloud.githubusercontent.com/assets/109954/26334619/1e85d1ce-3f1b-11e7-9a4c-76c66132f6c1.png)

### Step 4
![screen shot 2017-05-22 at 6 17 17 pm](https://cloud.githubusercontent.com/assets/109954/26334620/1e8951f0-3f1b-11e7-927c-cb8a9c705496.png)

Either granting permissions is failing (silently) or they are granted, but there is no way to know it and no way to remove them.

**Comment by jcoyne** [comment]
@atz are you pressing the "+" button in step 2?  I think that is required.

**Comment by atz** [comment]
That makes no sense.  `+` is to add *another* row, not to add the row just edited.

**Comment by mjgiarlo** [comment]
@atz @jcoyne is right. And you're right that we have misleading UX here.

**Comment by jcoyne** [comment]
So, this is fixed?  Should we open a new ticket about "the UI isn't great"?

**Comment by mjgiarlo** [comment]
That's my sense. @atz ?

**Comment by ggeisler** [comment]
For consistency and a better UI (specifically, I think the list of permission assignments should come after the controls for making assignments, since the latter take up a limited, fixed amount of vertical space, while the permission assignments could potentially be long), I'd suggest that the sharing/permissions section be rearranged similar to the layout in mockup in the Works Sharing section of this ticket: https://github.com/projecthydra-labs/hyrax/issues/695. So roughly like this (without the too-large headings...):

![6986d478-1876-11e7-92f1-b6b0ac2b4edd](https://cloud.githubusercontent.com/assets/101482/26372325/6f26a60c-3fb2-11e7-9da1-06218d8acb6d.png)

**Comment by atz** [comment]
Thanks, @ggeisler.  I agree that approach would remove the confusion.

**Comment by vantuyls** [comment]
@ggeisler's recommended approach has been implemented since this discussion. closing issue.
