### ISSUE TITLE
DerivativePath#all_paths is awfully inefficient

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#1057]
This is a really inefficient thing to do:

https://github.com/samvera-labs/hyrax/blob/0501634017f2c35a5cc3c007dd8d860b921a9cd3/app/services/hyrax/derivative_path.rb#L32

List _all_ the derivatives file paths (there could easily be tens of thousands or more), and check each one to see if it starts with something. I think there'd be a way to actually limit the Dir.glob to the prefix you want in the first place, and avoid a double traverse. 

Unclear how often this method is actually called though.

**Comment by mjgiarlo** [comment]
Thoughts on this, @awead?

**Comment by no-reply** [comment]
i don't think this is as inefficient as described. the `#root_path` return value is derived from the prefix. this logic is just dealing with the fact that the prefix may bleed into the filename (not just the directory).

we're traversing the directory that contains the current object's derivatives, which may contain the derivatives of a few other objects as well, and filtering to the relevant files. the number of files touched here is maybe 10s, rather than 10s of thousands.
