### ISSUE TITLE
Deleting a FileSet that provides a thumbnail (or representative media) should alert the user

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1110]
If I delete a FileSet in Hyrax and it's being used as the thumbnail or rep. media for its containing work currently, the work is without a thumbnail or rep. media and the user is none the wiser. Instead, we should:

1. Set the thumbnail, rep. media, or both (depending on what the FileSet was used for) to the first of work's members, if the work has remaining members; and
1. Render a flash message that lets the user know the actions taken in the prior step. We may need up to six messages here:
  * Deletion of thumbnail; thumbnail set to other FileSet. Edit work to change this.
  * Deletion of representative media; representative media set to other FileSet. Edit work to change this.
  * Deletion of thumbnail and representative media; thumbnail and representative media set to other FileSet. Edit work to change these.
  * Deletion of thumbnail; no thumbnail set because no other member FileSets. Add file(s) to work to change this.
  * Deletion of representative media; no representative media set because no other member FileSets. Add file(s) to work to change this.
  * Deletion of thumbnail and representative media; no thumbnail or representative media set because no  other member FileSets. Add file(s) to work to change these.

Check my math on the above, @jcoyne @tpendragon ?

@ggeisler Can you suggest strings to display to the user in the above scenarios?

**Comment by ggeisler** [comment]
@mjgiarlo See some general suggestions below. I'm not completely sure of the context in which these messages will be displayed (seems like it could be from the Work > Files tab, but maybe other places where files can be deleted?) so my text suggestions include options that depend on whether the context is the Work > Files tab (first option in the square brackets, where we can say "this work" because it's clear what the work in question is), or elsewhere (second option, where we should refer to the work by title and link that title so the user can easily follow the suggestion to edit it). 

Also, I'm assuming we will make the change proposed in https://github.com/samvera-labs/hyku/issues/1188, which I think simplifies this because when we direct to the user to "below" or "Files tab", they are in the necessary context for both adding a new file and updating the thumbnail and representative media selection.

Finally, feel free to modify my wording; I'm suggesting them without actually seeing the context so it's certainly possible they could be improved when seeing them in context. (I'm also not completely sure I understand when we refer to things as "fileset" versus "file".)

- Deletion of thumbnail; thumbnail set to other FileSet. Edit work to change this.

> FileSet successfully deleted. Because this FileSet served as the thumbnail for [this work | _linked title of work_], the work no longer has a representative thumbnail. [You can select another file to serve as the thumbnail below. | You can select another thumbnail to represent this work by editing the work and visiting the Files tab.]

- Deletion of representative media; representative media set to other FileSet. Edit work to change this.

> FileSet successfully deleted. Because this FileSet served as the representative media for [this work | _linked title of work_], the work no longer has a representative media file. [You can select another file as the representative media below. | You can select another file to represent this work by editing the work and visiting the Files tab.]

- Deletion of thumbnail and representative media; thumbnail and representative media set to other FileSet. Edit work to change these.

> FileSet successfully deleted. Because this FileSet served as the thumbnail and representative media for [this work | _linked title of work_], the work no longer has a thumbnail or representative media file. [You can select other files to serve as the thumbnail and representative media below. | You can select other files to represent this work by editing the work and visiting the Files tab.] 

- Deletion of thumbnail; no thumbnail set because no other member FileSets. Add file(s) to work to change this.

> FileSet successfully deleted. Because this FileSet served as the thumbnail for [this work | _linked title of work_], the work no longer has a representative thumbnail. To assign a new thumbnail for this work,
 [first add one or more files to the work below. | edit the work and visit the Files tab to add new file(s) to the work.]

- Deletion of representative media; no representative media set because no other member FileSets. Add file(s) to work to change this.

> FileSet successfully deleted. Because this FileSet served as the representative media for [this work | _linked title of work_], the work no longer has a representative media file. To assign a new representative media file for this work,
 [first add one or more files to the work below. | edit the work and visit the Files tab to add new file(s) to the work.]

- Deletion of thumbnail and representative media; no thumbnail or representative media set because no other member FileSets. Add file(s) to work to change these.

> FileSet successfully deleted. Because this FileSet served as the thumbnail and representative media for [this work | _linked title of work_], the work no longer has a thumbnail or representative media file. To assign new thumbnail and representative media files to this work,
 [first add one or more files to the work below. | edit the work and visit the Files tab to add new file(s) to the work.]

**Comment by mjgiarlo** [comment]
This should be taken up after https://github.com/samvera-labs/hyku/issues/1188.

**Comment by mjgiarlo** [comment]
Thanks, @ggeisler! There are two places to delete files, now, AFAIK:

1. From the Items list in the Work Show page
2. From the FileSet show page

https://github.com/samvera-labs/hyku/issues/1188 will add a third place.

The above looks great. Thanks, @ggeisler!

**Comment by atz** [comment]
#1188 is now #1147 and #1148

**Comment by mcdowney** [comment]
Closing in favor of tickets listed above
