### ISSUE TITLE
Add embargo/lease to dashboard

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1127]
### Descriptive summary

@mjgiarlo notes - after PR #1042 is merged, we should link the pages into our current dashboard. This will require one or more new tickets. Design-related questions:

- Where do we want embargoes and leases in the dashboard menu?
- Who should see the embargo and leave menu items? (It's currently limited to repo admins, and they can see all embargoed and leased works. Maybe that's OK for an initial implementation, and we need another ticket for letting admin set managers see them, including making sure the lease and embargo controllers and views only show admin set managers works in their admin sets?)

### Related work

PE #1042 

TODO items in #1123 might be better resolved after this design is done.

**Comment by hannahfrost** [comment]
@darrenleeweber @mjgiarlo @ggeisler 

To be clear, are we talking about a page that displays works currently under embargo or lease? 

Could it be a filter on the Works index page on the dashboard?

**Comment by mjgiarlo** [comment]
@hannahfrost I believe we already have the pages that show leases and embargoes but we have not yet linked them into the current design. We need to decide where this will live in the dashboard menu, what the label(s) will be, and who should see them (repo admins, or...?).

**Comment by ggeisler** [comment]
@mjgiarlo How can I see these embargoes and leases pages? The questions you ask above will be easier to answer if I have some idea of what these pages are for and what they look like.

**Comment by mjgiarlo** [comment]
@ggeisler You should be able to see them in your Hyku demo tenant by tacking `/embargoes` or `/leases` onto the URL, if you're logged in.

**Comment by ggeisler** [comment]
Okay, thanks @mjgiarlo. Based on what I see, it seems like we could use design needed tickets for both how these pages are accessed from the dashboard and for the pages themselves, which could use some additional work?

**Comment by mjgiarlo** [comment]
@ggeisler :rocket:

**Comment by hannahfrost** [comment]
@ggeisler I gathered some input from Hyrax Repo Managers regarding the kinds of things they do with these UIs, mostly related to embargoes. 

Admins need to review an embargoed work before the restriction is about to expire. Like to receive a notification. It may make sense to send them to this UI, instead of directly to the work page, because here they can also see other works that are pending release. And from here they can drill down to the detailed work page if necessary. 

Academic department staff (who may have a role in collection management) like to review embargoes applied at the time of submission. As above, it may make sense for them to use this UI to review a batch of newly submitted works with embargoes. 

Admins like to ability to review a work that has been embargoed and actively release it themselves, rather than have the release be automated. It provides them a more hands-on approach and the opportunity to communicate directly with the creator/depositor/author about the release. They also like to actively, manually release in bulk.

There is also interest in configuring a default embargo period and a maximum embargo period, across the repository or at the content type level. Is this UI the appropriate place to make those kinds of configurations?

**Comment by julesies** [comment]
@hannahfrost @ggeisler @mjgiarlo @vantuyls we'd like to make a PR to add Manage Lease and Embargoes on the Admin Dashboard. Are people okay with this? Here's a possible location under Tasks, happy to change implement a different icon:

![screen shot 2018-02-08 at 11 31 00 am](https://user-images.githubusercontent.com/4356335/35985093-cdc36176-0cc3-11e8-88ec-f1587c4caeb0.png)

**Comment by julesies** [comment]
@smithjp ☝️

**Comment by ggeisler** [comment]
@julesies Not sure if you've received more feedback from others via other means, but my thoughts are that, assuming the content of the Manage Leases and Manage Embargoes pages enables the kind of things @hannahfrost mentions in her [earlier comment](https://github.com/samvera/hyrax/issues/1127#issuecomment-328158079) (generally), then the Tasks section certainly seems like the right spot for those menu items to me.

**Comment by hannahfrost** [comment]
Makes good sense to me, @julesies. Sorry that I missed commenting earlier (and thanks, @ggeisler, for bumping it in my inbox!)
