### ISSUE TITLE
Remove Delete Work Option from Edit Collection Action Dropdown

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#1282]
### Descriptive summary

In Hyrax 2.0.0 alpha, we have the option to completely delete a work from the Collection edit page. This action should not happen at the Collection level.

### Rationale

We have the ability to _remove_ a work from a Collection, but we should not be deleting works from the Collection level. Deleting works should happen at the work level.

### Expected behavior

I should only be able to remove works from a Collection.

### Actual behavior

I can remove and delete works.

### Steps to reproduce the behavior

1. Create a collection or view a collection
1. Add some works
1. Edit the collection
1. From the listing of items in the collection select the drop down under the Actions column
1. Delete work is the third option in the drop down

### Related work

https://github.com/psu-stewardship/scholarsphere/issues/619

**Comment by mjgiarlo** [comment]
I'd like the @samvera/hyrax-ui-ux-advisors to chime in on this change, too.

**Comment by hackmastera** [comment]
I'm not sure I understand the argument for removing it. It seems like a cleanliness thing? But I suspect that my users use it from there. in a digital collections context you're going to be working from a collections view pretty frequently. I can check with them.

**Comment by mtribone** [comment]
@hackmastera Aaahhh. I can see your use case. We're a bit different since we are a self service repo with few collections. Made us say,"Danger Will Robinson" deleting a work completely from within the context of a Collection.

**Comment by newmanld** [comment]
Our use case is similar to @mtribone.  My initial reaction is to +1 this issue.  I think there is potential for our submitters to our self-submission repository thinking they were removing items from the collection, not deleting the works themselves.  In Hyrax 1.0.1, it looks like the 'Remove from Collection' option does not have an icon - this may increase the possibility that someone's eye will be drawn to "Delete Work" instead of "Remove from Collection."   

Was this functionality (ability to delete works from the collection show page) added between Sufia 7.3 and Hyrax 1.x?  I will check with our Product Owners to see if they see the same risk and to what degree.

**Comment by hackmastera** [comment]
I asked my 2 heaviest users. 

One said she will use the delete function anywhere she finds it, but that it makes intellectual sense not to have it here and so supports its removal.

One said it's convenient to be able to delete from here and would prefer to keep it, but she wouldn't be too annoyed if it were removed.

**Comment by no-reply** [comment]
wondering if @samvera/hyrax-repo-managers have opinions about this.

**Comment by mcdowney** [comment]
This has been amended and you can no longer delete Works from the Collection page. Closing.
