### ISSUE TITLE
Include more metadata in Facebook sharer

### ISSUE THREAD

**Issue by crowesn** [samvera/hyrax#1323]
### Descriptive summary

Hyrax 1.x - There's minimal metadata included in facebook sharer. The only thing visible is the base URL for the IR with a link to the full URL. Could add some [opengraph markup](https://developers.facebook.com/docs/sharing/webmasters) to views to customize content appearance on facebook

### Rationale

As a user, when I use the Facebook social media sharing icon, I want Facebook to display the title of the work.

### Expected behavior

Sharer should display a minimal set of metadata about the shared work. Title of work, maybe author, etc.

### Actual behavior

![screen shot 2017-07-07 at 11 54 50 am](https://user-images.githubusercontent.com/1069588/27965873-262052c4-630b-11e7-8a0f-52e27d07893b.png)

### Steps to reproduce the behavior

1. Visit any work show view
1. Click facebook icon to post to facebook.

Hat-tip @newmanld

**Comment by mjgiarlo** [comment]
See also #109. These elements are embedded currently on the FileSet show page (because this work preceded the creation of Works), but they should move (or be copied to, and possibly reworked) to the Work show page. I don't imagine this would be a big pile of work.

Thanks for writing up the issue, @crowesn (and @newmanld).

**Comment by mjgiarlo** [comment]
Fixed by #1324. Thanks for reporting, @crowesn @newmanld.
