### ISSUE TITLE
Collections: Update UI/UX of the listing of collections in the All/My Collections index

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1509]
### Descriptive summary

Update code that creates the listing of collections in the index view.

NOTE: This issue was extracted from the uber issue for index view changes.  #1417

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

Update the UI/UX of the listing of collections in the index views. 

From the All Collections and My Collections pages, a user can...
- [ ] see a list of existing collections and admin sets (see note below on AdminSets)
  - [x] the table for the listing should include columns... 
    - [x] Title - thumbnail and collection title
      - [x] for collections, the title links to `/hyrax/dashboard/collections_controller#show` action
      - [ ] for admin sets, the title links to `/hyrax/admin/admin_set#show` action
    - [x] Type - collection type (e.g. Administrative Set, User Collection, Exhibit, etc.) - This is the title of the collection type. #1570 
    - [x] Visibility - visibility of the collection (e.g. public, private, etc.)
    - [ ] Items - a count of sub-collections and works immediately within the collection (does not cascade to add the count of items in sub-collections)  Can creaet a separate ticket for this if complex, or put in a separate PR once the basic changes are committed.
    - [x] Last modified - TODO: Prefer last mod date, but can start out with `Date added` and enter a ticket to move to Last modified 
    - [x] Actions - actions to take on a collection (i.e., View collection, Edit collection, Delete collection, Add collection to another collection)  NOTE: The processing of actions are being added by other issues.
    
Exact text for collection list and action menu are in the mockup.

#### SPECIAL NOTE on Admin Sets:

For the initial implementation, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection.

To make the illusion happen...
* the search builder needs to retrieve both collections and admin sets to be displayed in the list of collections
    
### Mockup

See listing of collections and note 3 showing the Action menu

![collection-index-end-user](https://user-images.githubusercontent.com/101482/28932481-7932e160-782e-11e7-9baa-457e5c59fd97.png)

#### Issues related to UI work for nesting

* #1417 original UI epic for admin index
* #1509 admin index - listing of collections - includes description of action menu items
* #1512 process `Add collection to another collection` action + modal for selecting other collection  (This one has the brain dump list of things needed for nesting)
* #1377 relationship partial for edit form

#### Collections original epic issues (mainly organized by UI)

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | #1417 |
| Index: Collection List   | (this issue) |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | #1508 |
| Index: Delete Action     | #1507 |
| Index: Add as Subcollection Action | #1512 |
| Index: Bulk Actions      | #1510 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by respinos** [comment]
AdminSet solr document currently looks like 
```
{
        "system_create_dtsi":"2017-08-23T18:55:26Z",
        "system_modified_dtsi":"2017-08-23T18:55:26Z",
        "has_model_ssim":["AdminSet"],
        "id":"admin_set/default",
        "accessControl_ssim":["18183bb5-52fe-4ef3-a8f4-dea218928178"],
        "title_tesim":["Default Admin Set"],
        "thumbnail_path_ss":"/assets/default-f936e9c3ea7a38e2c2092099586a71380b11258697b37fb4df376704495a849a.png",
        "read_access_group_ssim":["public"],
        "edit_access_group_ssim":["admin"],
        "human_readable_type_tesim":["Admin Set"],
        "_version_":1576549249663893504,
        "timestamp":"2017-08-23T18:55:27.954Z"},
```

but the search builder for collections filters by `{!raw f=depositor_ssim}admin@localhost`.

**Comment by elrayle** [comment]
See issue specific to search builder...  

#1587 Collections: Modify My Collections search builder to return all editable collections and admin sets

**Comment by elrayle** [comment]
@ggeisler Should the Delete Collections button always be visible or only when one of the checkboxes is selected.  For other similar pages, the bulk actions only show up when there is at least one checkbox selected?

**Comment by elrayle** [comment]
@ggeisler Would the core collection actions be listed in the action menu first (e.g. view, edit, delete) and then list the nesting related action item (e.g. add selected collection to collection)?  I lean toward this instead of what the mockup shows because all collections support the core actions, where as, only nestable collections supports the add selected collection to collection action.

**Comment by ggeisler** [comment]
@elrayle 

> Should the Delete Collections button always be visible or only when one of the checkboxes is selected

I'd suggest it be always visible. Otherwise it is not clear to the user that bulk deleting is an available action. If the user selects the Delete collections button with no collections selected, you could display a modal message saying "You must select one or more collections before you can delete them."

As for the bulk actions button(s) only being shown in other places when at least one checkbox is selected, I'd suggest those should be updated to the match the behavior described above, for the same reason (I didn't design the current behavior so this is another case where I'm trying to make what I see as improvements rather than matching the current UI).

> Would the core collection actions be listed in the action menu first 

Sure, that seems fine to me. I put Delete last just because I assume it might be used less often than the other actions, and there is less chance of it being accidentally selected if it is at the end, but those are minor considerations and your rationale for a different order also make sense.

**Comment by elrayle** [comment]
@ggeisler One other clarification...

For single collection action `Add selected collection to collection`...
* should the label be `Add this collection to collection`?  `selected` may imply something to do with the checkbox which selects collections
* should the action be hidden or disabled when `collection.nestable? false`?  I have two thought on that.  If the site has 0 collection types supporting nesting, then it should be hidden.  If the site has at least one collection type supporting nesting, then maybe go with disabled.

**Comment by ggeisler** [comment]
@elrayle Are you looking at the mockup in this ticket? I'm confused because the note for the single collection actions menu (note 3) doesn't suggest the label be `Add selected collection to collection`. The word "selected" is not used.

I like the wording in my mockup better than `Add this collection to collection` because the "collection to collection" part seems unnecessarily truncated and possibly confusing. I think the "another" clarifies it.

As for the action being hidden or disabled when `collection.nestable? false?`, yes, I like your idea of hiding the action if the repository has zero collection types supporting nesting. 

If the repository does support nesting, disabling the action is okay and certainly better than hiding it only for types that don't support it. I think the ideal solution would be to not disable the action but when selected display a message saying "This type of collection does not support nesting so the collection cannot be added to another collection."

That way the user learns why they can't nest a collection, which won't be as clear if you just disable the action. But there are pros and cons with each approach, so I think either is acceptable.

**Comment by elrayle** [comment]
@ggeisler 

RE: Label - Thanks for the clarification on the label.  I didn't notice that the mockup was different from what I'm seeing in the UI for the PR for this issue.  I'll suggest the change.

RE: Hide vs. Disable - I like your suggestion of a pop-up explaining why they can't do that.  It gives the user more information since they will be able to do it for some collections, but not others.

**Comment by adamjarling** [comment]
Fixing the text for `Add collection to another collection` now...

**Comment by elrayle** [comment]
Remaining Work:
* calculate counts for items
* implement batch processing (clicking select all checkbox and the Delete collections button does not work in PR #1644)
* do not show `Add this collection to collection` in single collection action menu if there are 0 collection types supporting nesting

**Comment by elrayle** [comment]
All remaining work is either complete or represented in another issue.  Closing.
