### ISSUE TITLE
original URL for default background image 404s

### ISSUE THREAD

**Issue by dunn** [samvera/hyrax#1551]
The current value for [`background_attribution_html`](https://github.com/samvera/hyrax/blob/master/config/locales/hyrax.en.yml#L259) as of 181141da95e7f9efe5d5d7a1b8b38fed6c7c1ff9 links back to the Flickr source for the background image using https://flic.kr/p/eirxaf, which no longer resolves.

**Comment by mjgiarlo** [comment]
Hi, @dunn. We discussed this over in Hyku here: https://github.com/samvera-labs/hyku/issues/1167

And decided that instead of tweaking this, we would allow easier customization of the footer: https://github.com/samvera/hyrax/issues/189

What would you think of that as an alternative solution to this?

**Comment by dunn** [comment]
Yeah, as long as the default isn't a broken URL.

**Comment by mjgiarlo** [comment]
In the meantime, would you suggest removing the URL, replacing the image, or something else?

**Comment by dunn** [comment]
Probably replacing it, since attribution is required, right?  Unless we can track down the source.

**Comment by mjgiarlo** [comment]
@dunn correctamundo. OK. Now we just need to get someone to suggest an alternative image!

**Comment by ggeisler** [comment]
@mjgiarlo Forgive me if I'm not following this correctly, but if the issue is a default image for the site banner, I think we definitely should go with a default image that requires no attribution. For OR a few months ago I gave Hannah a selection of potential banner images (all free and requiring no attribution) to use for the OR demo. I wasn't there so not sure what was used or how well it worked, but I think this might have been one of the images she was considering:

![mountains](https://user-images.githubusercontent.com/101482/29949206-ffa60d2c-8e67-11e7-988d-4910b8787d56.jpg)

Would something like that work?

**Comment by mjgiarlo** [comment]
Perfect, @ggeisler! PR is in: https://github.com/samvera/hyrax/pull/1613

**Comment by ggeisler** [comment]
Although it doesn't require attribution, since we're going to use it I'll note the source and license information below (especially since I modified the original to work as a banner), just for the record.

Source: https://unsplash.com/search/photos/mountains?photo=X0OoHrPvgXE

License info: https://unsplash.com/license

<img width="972" alt="license___unsplash" src="https://user-images.githubusercontent.com/101482/29978779-6e64372c-8ef7-11e7-8f57-374a79570bb7.png">

**Comment by dunn** [comment]
Since they say they appreciate attribution when possible, we may as well add it.

**Comment by ggeisler** [comment]
@dunn I think that defeats the purpose of using an image that doesn't require attribution. We're trying to avoid having to maintain an attribution statement.

**Comment by dunn** [comment]
> We're trying to avoid having to maintain an attribution statement.

In case the URL goes dead again?

Beyond the wishes of the creator, it would be nice to have the default configuration show how that field is used.

**Comment by ggeisler** [comment]
> In case the URL goes dead again?

As I said in my original comment in this thread, perhaps I don't understand the whole context of this ticket. I'll just say that my intent when spending a couple of hours searching for and modifying images to come up with some viable candidates for a default site banner, my goal was to have a site banner that did not require attribution so that we would not have to keep track of and display an attribution link in the site footer. Displaying an attribution link to a non-affiliated person in an institutional website seems a little amateurish to me, and having to make sure that link remains viable seems like unnecessary overhead.

> Beyond the wishes of the image creator,

If the image creator was not okay with his or her image being used without attribution, I don't think he or she would have posted to a site that explicitly says all images on the site can be used without attribution. I'm not trying to cheat a content creator out of recognition. If I were using the image in a blog post or something I'd happily provide an attribution to go along with the image. In this context an attribution is intrusive, and not providing an attribution is not being disrespectful to a creator who posted an image under a license that explicitly does not require attribution, in my opinion.
