### ISSUE TITLE
Warn the user when works could not be added to a single-membership collection

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1567]
Currently there are two code paths that add works to collections: one goes through the `WorksControllerBehavior` and the other goes through the `CollectionBehavior`. The latter does all of its membership checking down in the model, with no shared context w/ the controller, so currently if the membership checker balks, there's no way to surface errors or warnings. We should warn users if a work is not added to a collection they have specified.

See:

https://github.com/samvera/hyrax/blob/2306ca16c6ad8bedf628310a097eddd8cedbed82/app/models/concerns/hyrax/collection_behavior.rb#L48-L52

**Comment by mjgiarlo** [comment]
@elrayle :point_up:

**Comment by blancoj** [comment]
I have done some work on this, but am not sure my approach is correct. @mjgiarlo suggested I use  `collection.errors.add(:collections, error_messages) if error_messages.any?` instead of `flash[:notice] = error_messages.join(" ") if error_messages.any?`, but I  I did not see the message show up.  This is where the message gets sent out:  https://github.com/samvera/hyrax/blob/coll-1567/app/controllers/hyrax/dashboard/collections_controller.rb#L138

If I use `flash[:notice] = error_messages.join(" ") if error_messages.any?` I see the message.

I have a branch of the work I've done: coll-1567.

**Comment by elrayle** [comment]
Note: This QA test fails to prevent a work from being added to two collections of the same Single Membership collection type.

Prereq: Create 2 collections of type Single-Membership C
* From Dashboard -> Works, check box beside any work not already in the two prereq collections
* Click Add to collection button
* Choose one of the two prereq collections
* Verify the work was added to the collection
* From Dashboard -> Works, check box beside several works including the same work just added to the first collection
* Click Add to collection button
* Choose the other prereq collection
* Verify the work added to the first was NOT added to second collection and a flash message tells the user why it was not added
* Verify the other works that are not members of the first collection were added to the second collection

**Comment by elrayle** [comment]
Fixed by PR #2640 and PR #2687

**Comment by mcwhitaker** [comment]
@elrayle -- In the current Hyrax QA testing scenarios, (see https://docs.google.com/spreadsheets/d/1XxG00RCkypCqLjfzx2RnoKLbZdaMxXMbW8A4hNHRrc0/edit#gid=1192600172 test CM_1.6) there is a question:

> Question: Should error message show when Add button is clicked OR when Save changes button is clicked.

This is confusing the testers. Currently, the user is warned when changes are saved. I don't know who added that question there, but the tester feels it should be when the add button is clicked. Is this still up for discussion or was a decision made?

Thank you.

**Comment by elrayle** [comment]
I read back through the steps above and I believe they are accurate.  Here is the challenge with changing this.

* The steps above take place in the dashboard.
* The first part puts a work in a collection of the single-membership type.
* The second part tries to add the same work to a collection that violates the single-membership rule.
* In the second part, multiple works are added to the collection at the same time.  Only one of these works violates the single-membership rule.

We can't provide a message when the Add Button is clicked for two reasons:
* We don't know yet which collection the user will select.  They may select one that is ok.
* We don't know which works will violate the single-membership rule until we try to save the work in the collection.

There is some wiggle room on the second.  The membership check could be performed as soon as a collection is selected and show the user a warning/error before they click save.

## Expected

Can you describe what the testers expected to happen?

From the description above, the expectation would be that all works without a violation are added to the second collection.  And an error message should be shown for the one work that could not be added because it violated the single-membership rule.

## Actual

Is the actual different from what I described under expected?

## Proposed changes

What would make this less confusing?

**Comment by mcwhitaker** [comment]
@jlhardes  was the one who brought this up. The testing spreadsheet asks the question, so it seemed that the tester could express their opinion. And Julie's opinion was that the warning should be when the file was added. But I see your point and I am sure Julie will see it with your explanation above. 

Conclusion: the testing spreadsheet should not have that question there. I will remove it.

Thank you very much for the clarification, @elrayle .
