### ISSUE TITLE
Collections: Modify My Collections search builder to return all editable collections and admin sets

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1587]
### Descriptive summary

My Collections list of collections should include all collections and admin sets for which the current user has edit_access.

### Rationale

Per UX redesign, My Collections will include all editable collections and admin sets.

### Expected behavior

The list of collections should include all collections and admin set for which the current user has edit_access.

### Actual behavior

The list of collections includes the collections the current user deposited.

#### Current Implementation
Search builder specified:  [app/controllers/hyrax/my/collections_controller.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/controllers/hyrax/my/collections_controller.rb#L4-L6)

Current Search Builder:  [Hyrax::My::CollectionsSearchBuilder](https://github.com/samvera/hyrax/blob/collections-sprint/app/search_builders/hyrax/my/collections_search_builder.rb)

which inherits from: [Hyrax::My::SearchBuilder](https://github.com/samvera/hyrax/blob/collections-sprint/app/search_builders/hyrax/my/search_builder.rb)

#### Proposed Implementation

Rewrite the search builder such that each of the following are included:  (pseudocode)

```
solr_parameters[:fq] << "edit_access_group_ssim:#{current_user.groups}"
solr_parameters[:fq] << "edit_access_person_ssim:#{current_user}"
solr_parameters[:fq] << "has_model_ssim:AdminSet"
solr_parameters[:fq] << "has_model_ssim:Collection"
```

The challenging bit is that the `edit_access_person_ssim` for AdminSets does not include the person who created the admin set.  Collections do put the depositor in the `edit_access_person_ssim`. 

And the thing that makes this even more challenging is that the AdminSet keeps the id of the person who created the AdminSet in the `creator_ssim`.  And the Collection uses `creator_tesim` for the conceptual creator of the collection.  This is not tied to a user in the system and does not grant the person identified in `creator_tesim` any access to the Collection.

`has_model_ssim:AdminSet` uses field `creator_ssim:user@email.com`
`has_model_ssim:Collection` uses field `creator_tesim:John Smith`

The question is, can solr docs other than Admin Sets have a `creator_ssim` field?  Is it safe to assume that if we find `creator_ssim:user@email.com` AND our current user is `user@email.com` then this is a positive match?

Question:   How to get solr to do an OR on a field like has_model_ssim?

### Steps to reproduce the behavior

1. Create a few admin sets with various group and user participants
1. Create a few collections with various group and user participants
1. Login as a user that has edit access to multiple collections and admin sets
1. Dashboard -> Repository Contents -> Collections

Verify that all collections and admin sets for which the current user has edit_access are included in the list.

### Related work

#1509 Collections: Update UI/UX of the listing of collections in the All/My Collections index

**Comment by elrayle** [comment]
@ggeisler With the definition that the My Collections tab should show all collections for which I have edit access, does this make the All Collections tab obsolete?
* only admins get both My Collections and All Collections tabs
* admins can edit everything
* THEREFORE, My Collections and All Collections have the same list of collections

RE: Viewer of Collections
* how does a user see the collections they can view?
* should My Collections list edit and view access collections with perhaps a marker that indicates what there access level AND an access filter: edit | view

Maybe we want a similar filter for owner: mine | others  (where mine is anything I deposited)

**Comment by ggeisler** [comment]
@elrayle No, I believe the current behavior is the way it should remain. We intentionally implemented the current All and Your tab behavior as part of the Hyku work. And, in fact, if you check you'll see it doesn't work the way you describe above in that the two tabs do not show the same list of collections. The current behavior is that for an admin, they see all collections in the repo under the All Collections tab (in the example, there are two collections in the repo, one created by the current admin user, one created by another user):

<img width="982" alt="collections" src="https://user-images.githubusercontent.com/101482/30389977-71f9302e-9869-11e7-9563-29231ab387ee.png">

 and only collections they created in the Your Collections tab:

<img width="987" alt="collections 2" src="https://user-images.githubusercontent.com/101482/30390016-90801efe-9869-11e7-8dcc-6a3639d13024.png">

The purpose of showing admins distinct tabs is so they can easily distinguish collections they have created (Your Collections tab) versus ones others in the repository have created. Otherwise the admin of a repo with many collections would have to do more work just to find one of their own collections. This was all previously designed and discussed.

As for viewing a collection, a user would see all the collections they can view using the public side of the repository, using search, browse, whatever we provide for viewing collections. Isn't that sufficient? I guess I don't understand the use case for providing an indicator of which collections a user can view.

(I'm also a little worried that you are referencing "My Collections." The "My" wording was changed quite a while ago and as you can see in the screenshots above, the tab should be called "Your Collections" in the current code. I hope you are not actually seeing "My Collections"?)

**Comment by jonathandixon** [comment]
Based on the description of this issue, the "Your Collections" and "All Collections" do become the same for Admins. This is because "Your Collections" is being redefined as all collections and admin sets for which I have edit access.

We could use some logic to use separate search builders for admins vs other users for the "your collections" tab, but I'm not a fan of that idea.

Another option would be to define the "Your Collections" tab as only collections or admin sets that you created, and introduce the "all collections" tab to all users. With the "all collections" tab containing any collection or admin set for which you have edit or view access to.

**Comment by ggeisler** [comment]
> Based on the description of this issue, the "Your Collections" and "All Collections" do become the same for Admins. This is because "Your Collections" is being redefined as all collections and admin sets for which I have edit access.

I don't think we should change behavior that a previous team intentionally debated and implemented because of how the issue is described. Maybe it is the issue description and "redefinition" that needs reconsideration.

> Another option would be to define the "Your Collections" tab as only collections or admin sets that you created, and introduce the "all collections" tab to all users.

Not an acceptable solution, in my opinion. If I'm a normal user and have created, say, three collections for my own purposes, finding them under a tab labelled "All Collections" would not be very intuitive.

**Comment by jonathandixon** [comment]
@ggeisler You're right. I think we need to compare the current implementation with this issue and figure out what changes, if any other than including admin sets, should be made.

Sorry, I wasn't clear on the "All collections" options:
- The "your collections" tab would include the collections/adminsets the user created.
- The "all collections" tab would include all collections/adminsets the user has edit or view access to. (which would also include everything listed under the "your collections" tab).

**Comment by ggeisler** [comment]
Okay, @jonathandixon that makes more sense. Though I still think we should first try to find a solution that adds admin sets as if they were collections, without changing any of the current behavior that determines what the user sees in each tab. Just because this was already thought-through and I worry about undoing previous decisions just to get admin sets added in (though I certainly acknowledge that that goal might be presenting difficult implementation challenges). 

(Especially since I'm likely the only one from the original work to define the behavior of these tabs that is paying attention to this work and I don't really have time to go back and dig into all the details.)

**Comment by elrayle** [comment]
@ggeisler The problem is that the current behavior is broken in comparison to functionality that was available in Sufia.  In Sufia, there was a `Shared with me` tab that listed collections/works created by other users to which I have `edit_access`.

For whatever reason, that was not pulled forward into Hyrax.  I never really cared for the wording of that tab, so I'm not advocating for its return.  I am making the observation that currently in Hyrax, a normal user does not have access to collections/works for which they have `edit access` through the dashboard listings.

This missing functionality was discussed previously which led to Your Collections tab being redefined to include all works a user can edit.  I am open to alternatives that address this.

I like @jonathandixon's suggestion for Your and All tabs behaviors.  It seems reasonably intuitive.

**Comment by ggeisler** [comment]
@elrayle If I understand correctly, I don't think think this functionality is missing in Hyku:

Example: Admin user sees three collections, last one is created by a normal user:

<img width="1248" alt="collections" src="https://user-images.githubusercontent.com/101482/30404459-a0ee2916-989b-11e7-9cf4-ebe75da13c1c.png">

Same repo, but this is what the normal user sees for collections:

<img width="1117" alt="collections 2" src="https://user-images.githubusercontent.com/101482/30404471-afdd7788-989b-11e7-99df-fa6fefff62b5.png">

Is there Hyku code that should/could be ported to Hyrax to help resolve this?

**Comment by elrayle** [comment]
### Actual Behavior
Your example is not the problem.  Admins are fine.  The problem is for normal users.

Scenario 1:  
* Normal user A creates Col_1, Col_2 and gives normal user B Manage access to Col_1.
* Normal user B creates Col_9.
* Admin user C creates Col_20

**--> Normal user B does not see Col_1 in Dashboard -> Collections**

Scenario 2:  Normal user A creates Work_1, Work_2 and give normal user B edit access to Work_1.

**--> Normal user B does not see Work_1 in Dashboard -> Works**

### Proposed Behavior

The proposal is that...

**--> Normal user A will see Col_1 and Col_2 in Your Collections** (2 user A created)
**--> Normal user A will see Col_1 and Col_2 in All Collections** (2 user A created + 0 shared edit)

**--> Normal user B will see Col_9 in Your Collections** (1 user B created)
**--> Normal user A will see Col_9 and Col_1 in All Collections** (1 user B created + 1 shared edit)

**--> Admin user C will see Col_20 in Your Collections** (1 user C created)
**--> Admin user C will see Col_20, Col_1, Col_2, Col_9 in All Collections** (all collections regardless of access)

same for works

### The original proposal as written in the issue

**--> Normal user A will see Col1 and Col2 in Your Collections** (2 user A created + 0 shared edits)
**--> Normal user B will see Col9 and Col1 in Your Collections** (1 user B created + 1 shared edit)
**--> Admin user C will see all collections in Your Collections** (all collections regardless of access)

With proposed filters:   Depositor: me | others

**Comment by elrayle** [comment]
From slack by @jonathandixon...

> That looks good. I would like to propose that in addition to what you have that All Collections also include collections for which the user has view access. I think it could be confusing to have a tab labeled “All Collection” but it not really include all the collections the user can discover.

**Comment by elrayle** [comment]
RE: read included in All...  Would this include collections where they are granted access as a Viewer or all collections they can read (e.g. visibility=public|registered + access=Viewer).  I do like the idea of having read collections in the All Collections tab.

They also need access to collections for which they can deposit.

**Comment by jonathandixon** [comment]
I would go with all collections they can read.

**Comment by ggeisler** [comment]
@elrayle You said:

> Your example is not the problem. Admins are fine. The problem is for normal users.

The second screenshot in my example **is** a normal user. My point is that the feature seems to work differently in Hyku than in the existing code you're looking at and thus maybe you should look at the code in Hyku before changing the behavior that you see in Hyrax.

In any case, please leave me out of further discussion. You seem to have a direction you want to go and it's taking too much of my time away from other projects to try to get my viewpoint across.

**Comment by elrayle** [comment]
I confirmed that Hyku behavior is the same as Hyrax.

To reproduce in Hyku:

1. Login as normal user A
1. Create 2 collections (Col_A-1, Col_A-2)
1. Login as normal user B
1. Create 2 collections (Col_B-1, Col_B-2)
1. Edit Col_B-2 and share edit access with user A  (Would be Manage access in Hyrax)
1. Login as normal user A
1. Dashboard -> Collections -> Your Collections

Notice that the list does **not** include Col_B-2 which user A can edit.  It only includes collections that user A created.

@hannahfrost @mjgiarlo Feedback Requested...

I would like to get feedback from Hyku designers before we move forward with a solution.  Two solutions have been proposed, but I will summarize the one that seems to have the most traction.

NOTE:  There is a subtle difference in access assignment in Hyrax in that a user can be a Manager, Depositor, or Viewer of a collection instead of simply being assigned edit or read access.

Proposal:
* All Users will have All Collections and Your Collections tab (admins and normal users)
* Your Collections will continue to only list Collections the user created.
* All Collections will include collections where you are a Manager, Depositor, or Viewer
* All Collections will have an additional filter to select `Access: Manager | Depositor | Viewer`

**Comment by ggeisler** [comment]
Again, I think we've already had this discussion in the context of Hyku and decided there was not a good reason for a normal (non-admin) user to have an All Collections tab. It sounds like the current (or at least I know the Hyku) code correctly shows a normal user's collections that they create, but doesn't show collections that were created by another user and then they were given edit access to. If that is an accurate understanding, then my question is, Isn't this just a bug where we need to update the Your Collections list to show all collections the user has edit access to, whether or not that user created the collection in the first place?

That is, I don't see any practical purpose, from the user point of view, in separating collections I can edit between two tabs/lists, just because some of them the user created and some of them the user didn't. In both cases **the user can edit them**, and that's what the user cares about when looking at their collections in the admin interface. There is a "Creator" field associated with the collection (I assume; at least, I included it in my mockups and no one said it isn't a valid field) so if for some reason I need to remember whether or not it was me that created this collection I can edit, it's there on the show page.

Under the proposal to show the user two tabs, the "Your Collections" tab is just a subset of what's shown in the "All Collections" tab, or could very likely even be an identical set if the user hasn't been granted  privileges to any collections besides the ones they created. This just makes the UI needlessly complex and adds to the cognitive burden (they have to visually process a UI with two main choices and decide which tab to look at) of the user who is going to the Collections page to find a collection to edit.

If I'm the only one that opposes the proposal to show all users both the "All Collections" and "Your Collections" tabs, feel free to ignore me; I'm happy to accept what the community agrees on here. But for the record I don't think it's the right UX decision.

**Comment by jonathandixon** [comment]
If this is true:

>  Isn't this just a bug where we need to update the Your Collections list to show all collections the user has edit access to, whether or not that user created the collection in the first place?

Then we just circle back to one of @elrayle original questions:

> With the definition that the My Collections tab should show all collections for which I have edit access, does this make the All Collections tab obsolete?

**Comment by elrayle** [comment]
@ggeisler 
> I don't see any practical purpose, from the user point of view, in separating collections I can edit between two tabs/lists, just because some of them the user created and some of them the user didn't.

Agreed

> This just makes the UI needlessly complex and adds to the cognitive burden

Agreed

> In both cases the user can edit them, and that's what the user cares about when looking at their collections in the admin interface.

Agreed and this is what led to the original proposal to have Your Collections show all collections a user can edit.  The impact of this proposal is...
* For a normal user, they will see Collections they created and Collections shared with them all under Your Collections.  
* For an admin, since they can edit everything, they will see all collections listed under Your Collections.  This means that All Collections and Your Collections has the same list of collections.  Which led to the question about All Collections being obsolete.

I was under the impression that you were opposed to seeing All Collections go away for the admin.  The alternate proposal was an attempt at a middle ground that kept Your Collections and All Collections in tack for the admin and extended the concept to normal users.

**Comment by elrayle** [comment]
I should note that the proposal includes the addition of a filter that would allow the admin to choose to see only the collections the admin created.

**Comment by ggeisler** [comment]
@elrayle I don't see where I gave you the impression that I wanted the All Collections tab to go away from the admin. In my first comment of this thread that includes screenshots, I provided an example from the current code of how the tabs look when there are two collections in the repo, one created by the current admin user, one created by another user. I provided the rationale for this approach in that comment and still think that is a reasonable approach.

> For an admin, since they can edit everything, they will see all collections listed under Your Collections. 

I don't understand how the current approach could include all collections that the admin has edit access for in the Your Collections tab, or you wouldn't see the result in my screenshots, where the admin user only has one of the two collections in her Your Collections tab. For the admin user, the Your Collections tab includes only collections the admin created. We previously decided this was necessary because a repo could have many, many collections and since the admin has edit access to all of them, the Your Collections tab would be the best way to help the admin find just the collections he or she created.

For a normal user, there isn't the need to distinguish between collections that user created and collections he or she can edit, because (unlike the admin) that user is unlikely to edit access to every collection in the repo. So for the normal user, just showing the Your Collections tab, with includes all collections that normal user has edit access to, seemed sufficient.

That's the scenario I believe we intended when we changed things in the past. It seems that there might be a bug/unimplemented aspect where for a normal user the Your Collections tab does not currently include collections that user can edit but didn't create. Aside from fixing that, that's the only change I see necessary, and that's what all my previous comments have been trying to convey.

Sure, you could dispense with the two tabs even for the admin and just add the filter you suggest for seeing only the collections the admin created. I wouldn't argue against that, but I think the two tabs make it more visible and clear to the admin how to see their collections, and the behavior supporting that is already there. Plus, if you dispense with the two tabs for the admin here, I think we'll need to do the same thing for Works or it'll be confusing why things are different there.

----
Alternatively, you could stick with two tabs for both the admin and normal user, and follow the suggestions for what goes into each tab (see Note 1 in each mockup) that I provided in my collection extensions mockups below (these weren't referenced in this ticket at all so I assumed you didn't want to implement those examples for whatever reason). I don't really care which alternative you go with, but I prefer both to your proposal to dispense with the All Collections tab for admins.

![admin-collections-index-administrator](https://user-images.githubusercontent.com/101482/30503840-996b98a0-9a20-11e7-8fbf-6b1f354724a9.png)

![admin-collections-index-end-user](https://user-images.githubusercontent.com/101482/30503845-9feb4338-9a20-11e7-9d86-c751f8b704c7.png)

**Comment by elrayle** [comment]
It sounds like you want different behavior for Your Collections for a normal user and an admin user.

> For the admin user, the Your Collections tab includes only collections the admin created.

> for the normal user, just showing the Your Collections tab, with includes all collections that normal user has edit access to

Is this correct?

**Comment by ggeisler** [comment]
Correct. Either that approach or the approach shown in the mockups provided above.

**Comment by hannahfrost** [comment]
@ggeisler @elrayle I have been following along with this thread today (finally) as time permitted and FWIW my preference lies in the approach portrayed in the mockups provided by Gary just a few posts above this post of mine here. 

I gather that part of the overall concern is how easy it is for the normal user, looking at the Your Collections tab as portrayed by Gary above, to easily distinguish collections that they created and those that they have been granted edit access to. Could we add a filter (next to "type" and "visibility") to help, a filter called "Created by me" (or something more elegant)?

**Comment by elrayle** [comment]
I missed note 1 in the mockup, which has likely led to much of the confusion in our conversation.  

I hope you can have patience as we sort this out.  It sounds like there were extensive conversations about the behavioral changes for the index page tabs by the Hyku team.  I'm not remembering having a specific conversation about the Managed Collections tab in the working group, but it could be I didn't have a good mental hook for it to plug into.  My thoughts up to this point have been based on how Hyrax currently operates and the need to adjust that.

## Interpretation of note 1

I interpret note 1, with the additional context of our conversation, as follows...

### For an admin:
> For the admin user, the Your Collections tab includes only collections the admin created.

> [All Collections includes] ones others in the repository have created

Note 1 doesn't specify that All Collections should be only ones others created.  When I read the label 'all', I expect the list will include all collections created by the admin and others.  Can I get clarification on this?

### For non-admin:
* Your Collections will be the same as for admin, showing only collection the user created.  (I couldn't find a supporting statement for this in the mockups or our discussions, but it seems to follow logically from the other discussions on tab content.)

* (My interpretation from note 1) Managed Collections shows collections for which the user has `:manage` access AND they did not create.  The Managed Collections tab is hidden if users do not have `:manage` access to any collections other than ones they created.  Based on...

> [note 1] If the user is not a repository manager/administrator, but has privileges to manage collections other than ones she created, this tab should instead be labeled "Managed Collections"

> [note 1] The first tab is not shown at all to users who can only manage collections they've created

### Did I get this right?  

I believe it is important that we have a shared understanding of the mockups before we can discuss anything beyond the mockups.  So my first question is does my interpretation of note 1 match your understanding?

**Comment by ggeisler** [comment]
@elrayle For the admin user, your interpretation seems right to me: the All Collections tab should include all collections the admin can manage, including ones that admin might have created.

For the non-admin, yes, the Your Collections tab would show only collections that user created. The Managed Collections tab would work as you describe.

**Comment by elrayle** [comment]
Great.  I'm glad we have the same interpretation.

The slight change I would propose is that for non-admin users, Managed Collections tab would include any collections where the user was assigned `:manage`, `:deposit`, or `:view` access.  And add a filter `access: Manage | Deposit | View`.

The rationale is that if a user is specifically added as a participant for a collection, then that collection is likely something that they have a higher level of responsibility for and want to be able to quickly find.

**Comment by ggeisler** [comment]
@elrayle Sure, no objection from me.

**Comment by elrayle** [comment]
For managed tab, collections and admin sets can be identified by...

`:manage` = `edit_access` in solr - `depositor=current_user`
`:view` = `view_access` in solr - `view_access: ['public', 'registered']`
`:deposit'` = query of permission_templates where current user has :deposit permissions

There is a service method, `Hyrax::Collections::PermissionsService.can_deposit_in_collection(user:, collection:)` that is currently stubbed that checks a single collection for deposit access.  We could probably add a new method `Hyrax::Collections::PermissionsService.can_deposit_in_collections(user:)` which returns a list of all collections in which a user can deposit.

**Comment by elrayle** [comment]
NOTE:

* Admin Sets use `creator_ssim` to identify the user who created the admin set.
* Collections use `depositor_ssim` and `depositor_tesim` to identify the user who created the collection.
* Collections use use `creator_tesim` to identify the user who is credited as the creator of the content in the collection.

**Comment by elrayle** [comment]
Remaining Work:

#1707 Do not show action `add collection to collection` to viewers on All/Managed Collections tab
#1507 Update code to handle deleting collections - specifically related to text shown in modals

**Comment by elrayle** [comment]
Requirements for this issue are met by PR #1655
