### ISSUE TITLE
Why does hyrax override app/views/catalog/_facet_limit.html.erb from Blacklight?

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#1623]
https://github.com/samvera/hyrax/blob/9928dcb88546013de506b89f13e694494b051453/app/views/catalog/_facet_limit.html.erb

https://github.com/projectblacklight/blacklight/blob/b2f7a223f648498658deba705fb5debe66e669dd/app/views/catalog/_facet_limit.html.erb

They are mostly the same. Sufia version seems to remove `data: { blacklight_modal: 'trigger' }` (and yet a modal is still triggered?), and adds `class: "more_facets_link"`. Any other differences?

If changes like this are needed, it seems it would be a lot better to submit them upstream to BL, rather than overriding for minor tweaks that don't seem sufia-specific. Excessive overrides makes maintenance and code archeology a lot tougher.

**Comment by mjgiarlo** [comment]
@jrochkind If I had to guess, we needed a seam for overriding something a long, long time ago and have updated this partial here and there since without considering whether it's removable. Do you have thoughts on this, @jcoyne? I suspect we could remove, if someone had cycles to make the change and see what effects it had.

**Comment by jcoyne** [comment]
No, if you think we can remove it, let's do it. 👍

**Comment by rjkati** [comment]
Closing as Hyrax and Blacklight are several versions out of date from when this ticket was written. If this is still an issue, please create a new ticket or reopen with updated information.
