### ISSUE TITLE
Collections: Clean up UI for select collection type modal when creating a new collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1645]
### Descriptive summary

The radio button and titles do not line up in the select collection type modal.  Tweak the modal to get it to match the expected mockup.

### Expected behavior

![image](https://user-images.githubusercontent.com/6855473/29412380-74ca0f92-8326-11e7-8aaf-03b8a2a19c6a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/6855473/29899589-595bbff0-8dba-11e7-99e5-4d9aa002380b.png)

### Steps to reproduce the behavior

1. Dashboard -> Collections -> New Collection

Verify modal matches expected mockup

### Related work

#1506 Collections: (HIGH) Show modal for selecting collection type when New Collection

**Comment by adamjarling** [comment]
@blancoj If you're interested in a solution that worked for me, check out https://github.com/samvera/hyrax/pull/1644/files, and look for the file (app/views/hyrax/my/collections/_modal_collection_types_to_create.html.erb).  

In attempt to keep files organized and small, I created a separate file for this modal, and am including it at the bottom of the index page next to the other modal file.  

I think the issue was modal classes (either `modal-body` or `modal-content`) was embedded in itself and used twice.
