### ISSUE TITLE
Date sorting on the Notifications page is not date sorting

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1653]
### Descriptive summary

The notifications page allows the notification table to be sortable by date (among other things) but the sorting on this field isn't actually sorting on date, it is sorting alphanumerically on the text in the date field. 

### Expected behavior
Sorting the Date field in this (or any) table should sort on date/time

### Actual behavior
Sorting the Date field in this table sorts alphanumerically

### Steps to reproduce the behavior

1. look at notifications tab
2. sort by date
3. alphanumeric!

**Comment by jcoyne** [comment]
@vantuyls what version? I thought this was fixed by https://github.com/samvera/hyrax/pull/1416

**Comment by jcoyne** [comment]
Ah, maybe `:long_ordinal` was a poor choice if the notifications span a month boundary.  Maybe `:db` would have been better.

**Comment by vantuyls** [comment]
this was observed on master.

**Comment by mjgiarlo** [comment]
@vantuyls I'd like to tag this with the 2.0.0 milestone, but that milestone is currently polluted with many many issues. Might you have time to work w/ me on clearing out that milestone so we can make it useful for us?

**Comment by vantuyls** [comment]
Can do.

**Comment by vantuyls** [comment]
see also: https://github.com/curationexperts/nurax/issues/33

**Comment by blackrat** [comment]
This seems to be a basic misunderstanding of how dataTables sorting works.
If you set a 'data-sort' option on the <td>, dataTables will use that for sorting rather than the generated content.

i.e. in _notifications.html.erb
`<td data-sort="<%= msg.last_message.created_at.getutc.iso8601 %>">`

will be sort by the iso8601 representation of the date as opposed to the underlying relative-time string. The (:long_ordinal) content will just be a default form displayed if the relative-time fails to correctly parse that datetime element.
