### ISSUE TITLE
Downloads of files uploaded via browse-everything (Box) have no file extension

### ISSUE THREAD

**Issue by kdid** [samvera/hyrax#1684]
### Descriptive summary

When you click the download link on the FileSet/Work page of a file uploaded via browse-everything, the downloaded file is just named 'download' with no file extension in Hyrax 2, or a hash starting with filesetid+date with no file extension in Hyrax 1.  

Files uploaded via the normal file upload form retain their original name + extension on the downloaded file.

### Rationale

This is problematic for end users trying to open the file. The file would need to be renamed first and a user may not know that they need to do this.

### Expected behavior

A downloaded file would have the original filename + extension

### Actual behavior

Downloaded file is named 'download' with no extension

### Steps to reproduce the behavior

* Visit a page containing a work or FileSet uploaded
* Click a Download button or link

### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
Can confirm this is an issue with Box and not with Dropbox, due to the path of the JobIoWrapper being set to `/tmp/some-long-string/download` instead of `/tmp/some-long-string/the-filename.pdf`. Don't currently have time to look into this further. Next step is to determine what component is setting the name of this path, and to see if it can instead access the original filename and use this instead.

**Comment by scherztc** [comment]
See what we did here locally to solve this :  https://github.com/uclibs/scholar_uc/pull/1663

**Comment by chrisdaaz** [comment]
note from https://github.com/curationexperts/nurax/issues/233

Retested after nurax was updated to 2.1.0.rc3. While the uploads now succeed, this issue is still present. I believe this might be the case for any browse-everything content and not just Box. I believe the culprit line is https://github.com/samvera/hyrax/blob/master/app/jobs/import_url_job.rb#L54. Instead of just assuming the url's path is the correct filename we may have to retrieve it some other way. The other possible candidate is in the downloads concern: https://github.com/samvera/hyrax/blob/master/app/controllers/concerns/hyrax/local_file_downloads_controller_behavior.rb#L46-L49

**Comment by dlim87** [comment]
QA - I don't have a box account to upload a test file, but assuming this work: https://nurax-dev.curationexperts.com/concern/generic_works/f1881k92v?locale=en is a box upload as it's name suggests, this is work properly. It's downloading the files with the same filename as the file has on the UI.

Tested on Mac: firefox, chrome, safari
Windows: firefox, chrome, edge
