### ISSUE TITLE
Collections: Parent and subcollections in collection show page

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1699]
### Descriptive summary

Need to include nested collections in the collection show page.  This includes showing the parent collection(s) and the sub-collections.

#### Parent Collections

We discussed having the parent collections display titles only near the top of the page, likely just below the title.

#### Sub-collections

There are two approaches on the table for sub-collections:

* OPTION 1: sub-collections are mixed in with works in the Items list
* OPTION 2: Works only are in the items list.  Just above or below the list of works is the list of sub-collections

Nuances for option 2:
Should the list of subcollections include...
* titles only with a link to the subcollection
* titles + items count (works + subcollections)
* titles + works count + subcollections count (similar to search results)
* full details like on collections index page

### Steps to reproduce the behavior

1. Add nested collections at least 3 deep
1. Go to show page for each of the collections

Verify that parents are shown as appropriate.
Verify that sub-collections are show as appropriate.

### Related work

TBD

**Comment by elrayle** [comment]
@ggeisler Any chance for a mockup for this?

**Comment by elrayle** [comment]
Parent from CurateND...

![image](https://user-images.githubusercontent.com/6855473/30607233-49647820-9d42-11e7-917b-ddb5af2f8c3f.png)

**Comment by elrayle** [comment]
Sub-collections from CurateND (just above list of works)...

![image](https://user-images.githubusercontent.com/6855473/30607292-72d3c382-9d42-11e7-994a-87384c8c7a29.png)

**Comment by laritakr** [comment]
This is sort of how it looks with collections mixed into the list. 

If we kept them mixed, we would likely want to add type to the list. In one list means one search instead of two, and includes the collections in the search results if searched. If we won't have a design for a while, I lean toward leaving them in the list until we decide, because it's simple for now and we won't be doing a bunch of extra work that we have to redo later.

![screen shot 2017-09-19 at 1 59 10 pm](https://user-images.githubusercontent.com/17851674/30607794-36589872-9d44-11e7-82a3-448ab297f1fc.png)

**Comment by ggeisler** [comment]
@elrayle I'm not sure I have time to do an updated mockup for this. I think someone needs to make some decisions first, such as whether it is more useful to separate works and sub-collections or list them in one table, as I think @laritakr's examples shows they are now.

If it is okay to separate works from collections, then another decision is whether for the collections it is necessary to put them in a table similar to works, or if they can simply be listed by title as in the ND example. Off-hand I think the latter approach seems pretty good, so the organization might be something like this:

- Collection metadata

Subcollections (heading)
- Collection title A
- Collection title B
- Collection title C

Works (heading)
- work action buttons
- sort and per page controls 
- works table

**Comment by elrayle** [comment]
That sounds good to me.  The only addition I might make is to include the item count after the subcollection title.  Perhaps in parentheses 
* `Collection title A (25)`
* `Collection title B (13)`
* `Collection title C (59)`

**Comment by ggeisler** [comment]
Yep, I like that idea. 

(Though what does the "item count" include if the sub-collection has both works and its own sub-collections?)

**Comment by elrayle** [comment]
@ggeisler I threw together a mockup (https://wiki.duraspace.org/x/4QRsBQ) that shows parent and sub-collections added to the admin show page.  Let me know what you think.  Questions that came up for me while putting it together...

* I like the distinctive way that CurateND set the heading for Parent Collection.  But we don't have anything like that anywhere else.  Other options would be to have the parent collection title beside the heading instead of under it.  Except that there can be multiple parents.  So maybe it does may sense to have a list under the heading.
* It would be great to have `Create new collection through this collection` button, but we don't have that functionality, so I only included the add existing link/button.
* What happens if there are more than 10 subcollections?  I included paginations for subcollections.
* Since search searches both subcollections and works, I put is above the sub-collections section.

**Comment by laritakr** [comment]
The metadata (#2) is currently two columns rather than just one. It was like that before, and I didn't bother to change it. Since there's space for that, you might want to think about whether or not we want that changed. If we don't add much metadata, there's no reason for two columns, but if there's a lot, it makes the page even longer and two columns might be more concise. 

In a similar light, perhaps two columns of collections so the list is shorter?  We could possibly do the left column for parents, and right for children, or parents first and then children?  I currently haven't coded anything regarding parent collections... my structure begins at the current one and branches down.

Also when you show a number by the collection title, be sure to define what it means... number of works in the collection? number of works AND collections? Only one level below, or all descendent members? If we have to do a lot of filtering to get the counts, is it worth it? If we don't filter and just use the count, is it confusing when they don't all show on the list due to permissions? I haven't done anything with the counts yet because I wasn't sure what was wanted, and nested collections just complicate it even more.

**Comment by ggeisler** [comment]
@elrayle Sure, this looks okay to me. It's going to be a busy page with all the various elements, but I guess we need them so that's probably unavoidable.

I like the parent collection heading approach. I personally don't think there is a need to indent the titles under the heading (nor under the Subcollections heading) since the heading is visually distinctive.

Regarding @laritakr's point about two columns for the collections list, I like that idea, although ideally you'd only go to two columns if there are more than say, five collections (because the second column could be less noticeable when there is only one or two items in it). You would probably also want to make sure the way the html is code is responsive, so that at, say, a tablet-width viewport and below, you revert to a single column, so that you aren't trying to squeeze two side-by-side columns with potentially long titles into a (for example) 500px width space.

**Comment by elrayle** [comment]
RE: counts... added a comment in the issue related to calculating counts.  #1670

**Comment by elrayle** [comment]
Mockup showing separation of Subcollections and Works...
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/6855473/31021796-f1562b68-a504-11e7-81a0-c5d061933d0e.png">

**Comment by elrayle** [comment]
Remaining Work:
* when clicking Refresh, forwards to public landing page instead of staying on admin show page
* Parent collection(s) are not shown under title (see mockup)

**Comment by laritakr** [comment]
A few comments on remaining work you listed above:

> parent collection(s) are not shown under title (see mockup)

I'm still concerned about this on the mockup. This is fine if there is only one, but the mockup shows the parent collections in the description area, and if there is a list rather than just one, I believe that wouldn't really work. My preference would be a modal link there to either the parent if there is only one, or to a list of parent collections if there are multiple.

> if no sub-collections, don't show the sub-collection section instead of writing a message that there aren't any sub-collections

I already omit the section if the collection isn't nestable. Perhaps the message isn't necessary, but the button to add collections is in that same section, so the section does sort of apply. In addition, the message appears when you search (the search bar searches both subcollections AND works, so both show a message if there were none found.) 

> include count of sub-collections

This should be "include count of the members of a subcollection. I already included the count of the subcollections.

**Comment by laritakr** [comment]
### Checklist of remaining work:
- [ ] when clicking Refresh, forwards to public landing page instead of staying on admin show page
- [ ] when searching, forwards to public landing page instead of staying on admin show page
- [ ] parent collection(s) are not shown under title (see mockup)
- [ ] parent collections list needs to be able to paginate
- [ ] sub-collections list needs to be able to paginate
- [ ] include count of number of items in each sub-collection in list

### Still needs design:

> If no sub-collections, don't show the sub-collection section instead of writing a message that there aren't any sub-collections

This needs more UI design to decide if it's a desirable change and how to accomplish it. The Subcollections section ONLY appears for a nestable collection. With this distinction in mind, making this change would trigger the following questions:
Where could we put the button to add a subcollection to the collection if we don't show this section when there are none?
How should it look if there are no subcollections returned by the search for a collection which has subcollections? Do we remove the section for that situation? 

It is my opinion that removing the Subcollections section on a nestable collection creates more complicated code that isn't justified by a slightly less complicated UI.

**Comment by elrayle** [comment]
The errors with sort by, show per page, and refresh were fixed in PR #2589.

**Comment by mcdowney** [comment]
Closing post collections work
