### ISSUE TITLE
Refactor: Add Managed tab to Dashboard -> Works

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1705]
### Descriptive summary

Dashboard Collections were refactored to add a Managed tab that shows users collections they did not create for which they have additional responsibilities through access grants.  This issue looks at doing the same work for Works.  See comments below for Related Work.

### Rationale

Collections and Works should have similar behaviors in the Dashboard.

#### For an admin:

* Your Works includes only works the admin created.
* All Works includes ones others in the repository have created.

#### For non-admin:

* Your Works includes only works the user created. (same as for admin users)
* Managed Works includes works for which the user has...
    *  `:edit` access either individually or by being in a group MINUS any the user created
    * `:read` access either individually or by being in a group MINUS groups ['public', 'registered'] (i.e., read access set through visibility)

#### Implementation

* Changes are required to the UI to show the various tabs.  Several partials need to change to make this happen.  See UI changes made for collection tabs as a starting point.
* Update/create search builder to find works for the Managed Works tab

### Steps to reproduce the behavior

1. Create admin user A, and normal users E and R
1. Login as user A
1. Create 3 works... work_1, work_2, work_3
1. Give edit access to work_1 to user E
1. Give read access to work_2 to user R
1. Login as user E
1. Create 1 work...  work_E and give read access with user R
1. Dashboard -> Works

Verify that work_E is the only work shown on Your Woks tab
Verify that work_1 is shown on Managed Works tab

1. Login as user R
1. Dashboard -> Works

Verify there are no works on Your Works tab
Verify that work_2 and work_E are shown on Managed Works tab

1. Login as admin user A
1. Dashboard -> Works

Verify there are 3 works on Your Works tab... work_1, work_2, work_3
Verify there is 4 works on All Works tab... work_1, work_2, work_3, work_E

### Related work

#1587 has a lengthy discussion on the Dashboard -> Collections tabs.  I'd look near the end for the comment with the heading "Interpretation of note 1" which gives a good summary of the tabs and what is shown on each and which users see the various tabs. 

PR #1655 has the code changes for the Dashboard -> Collections tab.  The code for works will be similar.

**Comment by elrayle** [comment]
@ggeisler Can you confirm that the description in this issue matches what you expect?  This adds the Managed Works tab to Dashboard -> Works with behaviors that match those for Dashboard -> Collections -> Managed Collections.

**Comment by ggeisler** [comment]
@elrayle Sure, that sounds fine to me, except I still don't understand the need (for either collections or works) to show the user all works/collections that user has `read` or `view` access to. I asked this question in an early comment in the [collections ticket thread](https://github.com/samvera/hyrax/issues/1587) and don't think you ever addressed it:

> As for viewing a collection, a user would see all the collections they can view using the public side of the repository, using search, browse, whatever we provide for viewing collections. Isn't that sufficient? I guess I don't understand the use case for providing an indicator of which collections a user can view.

I'm not saying I absolutely think there is no reason to show the user collections/works they have `read` access to on the admin side, but I'd like someone to explain how this is useful, given the user can easily see everything they have read access to on the public side of the site, and if they only have read access there is nothing they can do but look at it, so it doesn't feel like something they need to see within the admin pages. 

The obvious downsides of including every collection/work a user can only `read` in the "Managed" tab are 1) the label is no longer accurate, since they can't "manage" objects for which they only have `read` access to, and 2) the list of objects in the "Managed" tabs is likely to be much, much longer than if we excluded `read` objects, making the use of the tab much less efficient.

**Comment by elrayle** [comment]
For clarification, the only `read` access collections/works included in Managed Collections are the ones that the user is specifically granted through collection participants Viewer or through works sharing read access.  If a collection or work is singled out for sharing view access, that seems significant and the user is likely to have a higher interest in having access to that item.

The managed tab does not include collections/works where the user has read access through visibility = public or registered.

**Comment by ggeisler** [comment]
@elrayle Oh, okay, that's less of a concern then.

I wasn't taking into account read access being included when I came up with the label "Managed." I don't have any better ideas at the moment. I think it might be okay to continue to use it, unless someone comes up with a better idea, since the list is unlikely to include many objects the user can't actually manage.

**Comment by elrayle** [comment]
All requirements of this issue are met by PR #1749.
