### ISSUE TITLE
Collections: Populate edit Relationships tab with list of parent collections and sub-collections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1719]
### Descriptive summary

Get the list of parent collections and sub-collections for a collection from the nesting API.  Populate these lists in the `Relationships` tab of the collection edit form.

### Implementation

Update `app/views/hyrax/dashboard/collections/_form_relationships.html.erb` partial to... 
- [ ] use the nesting api to get the list of sub-collections
- [ ] use the nesting api to get the list of parent collections. 
- [ ] use the nesting api to add a sub-collection.
- [ ] use the nesting api to add a parent collection. 

### Steps to test the behavior

1. Create a collection type that allows nesting via Dashboard -> Settings -> Collection Types
1. Create 3 collections of that type via Dashboard -> Collections -> New Collection -> select that new type -> add title and save.  Assign titles 'A', 'B', 'C', 'D', 'E'
1. From Dashboard -> Collections, click the action menu for collection 'A'
  1. select `Add collection to another collection` and
  1. select collection 'B'
1. From Dashboard -> Collections, click the action menu for collection 'B'
  1. select `Add collection to another collection` and
  1. select collection 'C'
1. From Dashboard -> Collections, click the action menu for collection 'B' and 
  1. select 'Edit collection'
  1. click 'Relationships' tab

- [ ] Verify that the parent list includes collection 'A'.
- [ ] Verify that the child list includes collection 'C'.
- [ ] Verify that the select list for parent collections is populated with all possible parent collections = all collections of this type - current subcollections - current parents... ['D', 'E'].
- [ ] Verify that the select list for subcollections is populated with all possible subcollections = all collections of this type - current subcollections - current parents... ['D', 'E'].

1. Select 'D' as parent collection and click Add

- [ ] Verify the parent is added to the list of parents... ['A', 'D']

1. Select 'E' as subcollection and click Add

- [ ] Verify the subcollection is added to the list of subcollections... ['C', 'E']

### Related work

#1377 Add relationships tab to collection edit form
PR #1702 Update UI for relationship tab

**Comment by laritakr** [comment]
@elrayle I have some concerns about this design. Something just feels wrong about it. We are mixing the editing of an object with the creation and removal of its relationships to other objects. 

This concern is the same type of situation that I mentioned in my document on PR 1894 (where the list of works really shouldn't be there), except with collections rather than works. This goes far beyond the purpose of an "edit" function, and adding it into the collection controller isn't an option as far as I'm concerned. Those controllers are already a bit of a nightmare and this is not a collection function, it is a collection relationship function. 

Maintaining relationships to the object seems like it should happen from the object's show page. We already have the ability to add and remove member works, and add nested collections. Could we somehow add in removing nested collections as well? If that were the case, we wouldn't even need to manage the relationships as we edit the object itself. 

Do we know if every tab is a separate update, or do we combine updates from one tab to the next? If we can combine updates and send them all in one transaction, I am even more concerned with adding in the relationship edits, as these are not actually part of editing a collection. The edit function in the controller uses collection-params to decide what is being edited and respond accordingly, and I really hate making this even more confusing, but if the tabs aren't handled independently, this design would require them to be integrated.

Tagging @jeremyf and @jgondron for additional input or suggestions

**Comment by jeremyf** [comment]
As @laritakr was explaining this, it sounds like the edit controller action is already assuming multiple responsibilities; I'm hesitant to overload that action even more with switching logic based on the tab.

I believe it highlights that we should look at extracting a controller that deals with permissions, one that deals with relationships, etc. This would assist in breaking apart responsibilities. It would also point towards a defined API for the application. I believe we could then look at more generalized concepts (e.g. the Relationship resource for which we could send file_sets, works, and collections through, and rely on a factory/strategy pattern to implement the business logic of what it means to relate a Collection to a Work)

**Comment by elrayle** [comment]
@jeremyf @laritakr I agree.  For now, lets...
* populate the tab with the existing parents and children
* NOT include a way to add parents and children from this tab

It will be expected that nesting of collections is managed through the index and show pages.

**Comment by elrayle** [comment]
@laritakr Has all remaining work been captured in new issues?  If so, is this ready to close?

**Comment by laritakr** [comment]
@elrayle Yes, I believe that I covered all the remaining work in those three issues, so this issue can be closed.

**Comment by elrayle** [comment]
Fixed by #2257
