### ISSUE TITLE
Allow footer to be customized via ContentBlock

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#189]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Nov 17, 2016 at 20:07 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2916_

----

This provides an easy way for users to customize the look and feel of their applications.

**Comment by ggeisler** [comment]
@mjgiarlo Do you have any thoughts about how structured or unstructured you see the footer being? In other words, probably the easiest and most flexible way to handle this is to simply add a new tab called "Site Footer" to the Content Blocks page. The form on that page could contain the default footer content (so there is content unless and until the admin overrides it) but otherwise it is up to the admin to figure out how to get their desired content to look and lay out the way they want. The downside is people could come up with some pretty ugly results trying to use the limited features of the TinyMCE UI to get the arrangement of elements they want. (Though if they stick pretty closely to the layout of the default content, it would probably be fairly easy for them to produce a decent-looking footer for their institution.)

Is this along the lines of what you had in mind?

**Comment by mjgiarlo** [comment]
@ggeisler I hadn't thought about it very deeply, tbh. What you suggest sounds reasonable to me. One addendum: what if we already provided an automagic button for users to restore the default site footer content if they really get in a mess?

**Comment by ggeisler** [comment]
Yeah, I think that's a good idea. I can do a simple mockup just so the plan is clear.

**Comment by mjgiarlo** [comment]
@ggeisler Perfect. Thank you, sir.

**Comment by jcoyne** [comment]
FWIW, we presently have four content areas on the footer (2 are sort of customizeable using i18n)

**Comment by no-reply** [comment]
Closing this is lieu of design.
