### ISSUE TITLE
Make manager/depositor/viewer permissions more clear

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2005]
It's very unclear that a manager, depositor, viewer can only see those works that are deposited after they gain permissions to the admin set. I think we need to add language in this screen to make it clear. This has been a surprise to many testers, so I thought I'd write this up as a minimal thing to do before a larger effort happens.

Suggest something like this:
Individuals granted permission below will only have access to items (works?) deposited after their permission is granted.

**More comments at:**

https://github.com/curationexperts/nurax/issues/120

**Comment by ggeisler** [comment]
I think this is always going to be confusing because the behavior (only seeing works deposited after your role is granted) is very unintuitive. Assuming there is a good technical reason why we can't fix that behavior (or some good reason for the behavior that I don't understand), I agree adding some explanatory text could at least mitigate the confusion a bit.

I assume the "screen" in question is the Participants tab of the Edit Administrative Set page? If so, I'd suggest adding the new text below the "Add user" form elements (if I understand correctly that this caveat doesn't apply to people gaining permissions through a group).

<img width="970" alt="edit_admin_set____hyku" src="https://user-images.githubusercontent.com/101482/32200636-ea83386e-bd8f-11e7-9448-fc36fcf7568c.png">

```
<p class="help-block">Users granted a new role will only see works that are deposited after that role has been granted.</p>
```
