### ISSUE TITLE
valid_delete? for permission_template_access should allow delete for :view and :deposit access

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2259]
Branch: master

### Descriptive summary

Hyrax::Admin::PermissionTemplateAccessesController #valid_delete? method prevents users from deleting the required admin_group managers.  It also prevents removing admin_group for viewers and depositors, but it shouldn't.

### Rationale

Admins have viewer and depositor access as managers.  A user can still add the admin_group as a viewer and/or depositor.  After adding, they should be able to remove the admin_group from viewer and depositor roles.

### Expected behavior

After adding the admin_group as a viewer/depositor, the user should be able to remove the admin_group from that role.  The Repository Administrators should be removed from the list of Viewers/Depositors.  And a flash message should display stating: 'The administrative set's participant rights have been updated'.

### Actual behavior

After adding the admin_group as a viewer/depositor, the user can NOT remove the admin_group from that role.  Clicking Remove causes flash message: 'The repository administrators group cannot be removed.' and the Repository Administrators remain listed under Viewers/Depositors.

### Steps to reproduce the behavior

1. Login as admin
1. Dashboard -> Administrative Sets -> click title of an admin set -> Edit -> Participants tab
1. group: admin  role: Depositor --> Add
1. click Remove beside Repository Administrators in Depositors list

- [ ] verify that Repository Administrators was removed form the list of Depositors
- [ ] verify a flash message is displayed: 'The administrative set's participant rights have been updated'

Repeat test for role: Viewer

### Related work

#2214 Don't allow the admin permission to be revoked
#2077 remove permission_template and permission_template_access entries when permission_template is deleted

**Comment by mjgiarlo** [comment]
@jcoyne inclined to have another go at this?

**Comment by rjkati** [comment]
This issue is still present in Hyrax 3.0.0 rc3

**Comment by jeremyf** [comment]
I have to wonder if #4497 might fix this.  I have a branch up and running for that PR, I'll be spending some time trying to reproduce.

**Comment by jeremyf** [comment]
The primary logic in play is:  https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/hyrax/admin/permission_template_accesses_controller.rb#L22-L31

My understanding of the desired behavior by describing this another way is that we want to allow a user to rollback a change that they made.  What I'm also wondering, based on the requirement, is that this particular user should not be able to add the admin_group (e.g., they're already assigned so this doesn't make sense).

Looking at the history we are in our current application logic state based on  5ac59450283bb6085834a1b21e23d80f6687a139 which came about with PR #2077 for issue #2213; which was removed in #2077.

This ultimately strikes me that we should be answering the "can I delete this" in the permissions template ability class:

https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/models/concerns/hyrax/ability/permission_template_ability.rb#L9-L14

The current implementation (e.g. by checking `if valid_delete?`) in controller again slips authorization logic out of the Ability class.  But that's not quite the case, because we do the confusing add an error message, yet continue with the remove access, and finally call the `after_destroy_error` method: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/hyrax/admin/permission_template_accesses_controller.rb#L7-L18

**Comment by jeremyf** [comment]
Proposed solution:

1) Remove the in controller method permission check; That belongs at the authorization layer (e.g. `::Ability` class)
2) Compress the two steps of logic (e.g. destroy the instance, then call the form to do things) into a single step of logic.
3) Begin discussing the general solution in regards to the authorization layer and not custom guard checks in the controller.
4) This may mean that we expose a configuration option for deletion, but that's implicit in the method composition so that's premature optimization.

**Comment by abelemlih** [comment]
✅   @jlhardes This ticket passed QA testing, and ready to move to `Done`
