### ISSUE TITLE
Failing migrations for mysql starting at migration CreateUploadedFiles

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2347]
Branch:  master

### Descriptive summary

Migrations fail at CreateUploadedFiles when trying to create a new hyrax app using MySQL

### Rationale

Migrations should work for MySQL

### Expected behavior

All migrations should succeed.

### Actual behavior

CreateUploadedFiles migration fails for MySQL.  NOTE: It passes with engine_cart and sqlite.  It passes for postgres.

```
== 20171211132828 CreateUploadedFiles: migrating ==============================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:uploaded_files, {:id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'hyrax_migrate_development.uploaded_files' doesn't exist: SHOW FULL FIELDS FROM `uploaded_files`
```

### Steps to reproduce the behavior

1. Remove `rake db:migrate` from hyrax generation template (https://gist.githubusercontent.com/elrayle/3250233bf21cec3f1086c44d56eefea2/raw/e185d17bd2f0936bae34ec0fd5c22653d57fc090/hyrax_new_template)
1. generate a new hyrax app with mysql as the db
```
rails new myapp -m https://gist.githubusercontent.com/elrayle/3250233bf21cec3f1086c44d56eefea2/raw/e185d17bd2f0936bae34ec0fd5c22653d57fc090/hyrax_new_template -d mysql
```
1. update config/database.yml to work with your mysql
1. rake db:drop     (if needed to clear out previous creation of the tables)
1. rake db:create db:migrate

Migrations should complete without errors.

**Comment by elrayle** [comment]
There needs to be documentation on the recommended steps to create a hyrax app with an alternate database.  The README only describes creating a hyrax app with the default (sqlite) database.

**Comment by elrayle** [comment]
It was suggested that I not use the template for creating a new hyrax app that connects to MySQL.  I get the same error when I do not use the template.  Steps for creating without the template.

1. `rails new myapp -d mysql`
1. edit Gemfile and add `gem 'hyrax', '2.0.0'`
1. `bundle install`
1. update config/database.yml to work with your mysql
1. `rake db:drop`  (if needed to clear out previous creation of tables)
1. `rake db:create`
1. `rails g hyrax:install` 
1. `rake db:migrate`

Get the same error.

**Comment by mjgiarlo** [comment]
I could not reproduce this error.

**Comment by mjgiarlo** [comment]
I could reproduce this error when using Rails 5.1 (and MySQL, obviously).

**Comment by mjgiarlo** [comment]
The problem seems to be that the default column type for primary keys changed in Rails 5.1 from `:integer` to `:bigint`. There is a bug in Rails about this: https://github.com/rails/rails/issues/30806

It only seems to affect the MySQL adapter. SQLite and Postgres are not affected.

**Comment by mjgiarlo** [comment]
Here is a list of steps you can take to get around this error. I am not advocating for any of these as a solution in Hyrax, but rather listing what I know so we can share an understanding of the underlying situation:

* Add `type: :bigint` tohttps://github.com/samvera/hyrax/blob/master/db/migrate/20160401142419_create_uploaded_files.rb#L5 (and also https://github.com/samvera/hyrax/blob/master/db/migrate/20160427155928_create_operations.rb#L10)
* Modify the Devise create_users migration to force `type: :integer` for the PK of the `users` table
* Modify the Devise create_users migration to subclass `AR::Migration[4.2]`instead of `AR::Migration[5.1]`
* Modify affected Hyrax migrations (`create_operations` and `create_uploaded_files`) to subclass `AR::Migration[5.1]` instead of `AR::Migration[4.2]`

I was wondering if it might be defensible to tweak Hyrax to ship migrations that include logic to specify the "right" version of migration depending on the version of Rails present.

Would that fix things?

It would for new installations of Hyrax, but if I have an app that was upgraded from Rails 5.0 (*i.e.*, used the pre-5.1 Devise `create_users` migration, which means the `users` table has an `int(11)` PK), and then I `db:migrate` using a 5.1 version of the `uploaded_files` migration, I would expect the migration to fail because it'd see Rails 5.1 and thus subclass `AR::Migration[5.1]` and thus use a `:bigint` PK but the `users` table would use an `:integer` PK. Alternatively, I don't think it's possible to use a Hyrax based on Rails 5.0 that **hasn't already** run the affected migrations, so it could be the only folks affected by this are new installations using Rails 5.1 and MySQL.

**Comment by mjgiarlo** [comment]
Needs backporting so a 2.0.1 release can be made.
