### ISSUE TITLE
locales   hyrax.??.yml  files out of sync 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#2444]
### Descriptive summary

hyrax.??.yml files should have identical entries >  went through the locales in HEAD an found some missing/additional/not-removed entries. Backtracking this (see below section Related Work) I see the problem when entries in hyrax.en.yml are deleted but not in all the other  hyrax.??.yml files. 

### Rationale
Must make sure having the same  l18 variable entries in __all__ the hyrax.??.yml files when PR get accepted.  If possible a test would be ideal.  

### Expected behavior
Block merging PR's if a l18 variable entry or block in hyrax.en.yml got deleted but at the same time the corresponding ones in the hyrax.??.yml files are not.

### Actual behavior
There is no (blocking) check when a l18 variable entry or block in hyrax.en.yml got deleted but not the corresponding ones in the hyrax.??.yml files.

### Steps to reproduce the behavior

1. '''diff hyrax.??.yml''' in the current version (commit 28f8773a63100cc3169bcfda52f777914123c911)
1. hyrax.en.yml bisecting commits starting from the current version (commit 28f8773a63100cc3169bcfda52f777914123c911) tracing back to th commits (see below) 

### Related work 
I created some comments to the PR's questioning the purpose.
* https://github.com/samvera/hyrax/commit/f7ef416772b4e7df4e34ce031f71f93aaf197fdc#r26461437  
* https://github.com/samvera/hyrax/commit/27c405d924b046cbe755ff79864bfe60f1b21fc3#r26461527 
* https://github.com/samvera/hyrax/commit/1743c7b569b37cc3cb5d8aff441dedd87c35d744#r26475591
* https://github.com/samvera/hyrax/commit/18557e5ee4ca602d7a320b6fb91f3596326487f7#r26475664
* https://github.com/samvera/hyrax/commit/36f44803dd1fdbb06f7022d6ed5b4156823fcaf8#r26476187
* thats all so far, except missing translation two entries

**Comment by mjgiarlo** [comment]
@jmfrenzel See the following PR: https://github.com/samvera/hyrax/pull/2460

And the updated documentation: https://github.com/samvera/hyrax/wiki/Translations-(internationalization)#update-translations (step 3, which I added, in particular)

Per current practice, I would like to address this at point of release rather than at point of PR to reduce the burden on PR authors. (This is addressed by step two here: https://github.com/samvera/hyrax/wiki/Release-management-process)

How would the above work for your purposes, @jmfrenzel? Thanks for looking into this!

**Comment by jmfrenzel** [comment]
That makes sense for me, @mjgiarlo .Thanks.

**Comment by mjgiarlo** [comment]
and thank you too, @jmfrenzel!
