### ISSUE TITLE
Ensure collection of download counts independently of analytics platform

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2539]
### Descriptive summary
Download counts probably need to be tracked on the Hyrax end and can't accurately be provided by Google or Piwik.

**Comment by mcritchlow** [comment]
I'm curious to hear more about this. At the moment, Hyrax is sending downloads via [ga_events.js](https://github.com/samvera/hyrax/blob/53003f89e199e5c08a20318556be895207bebca1/app/assets/javascripts/hyrax/ga_events.js#L7) and the resulting Legato model code/filter querying for those downloads expects them to have been sent in that specific way.

So is the issue that the additional type of download tracking can't be handled via this method, or that Piwik/Matomo doesn't support a similar mechanism? Or is it that we just think it's easier to have this handled in-house, so to speak?

I ask because this seems relevant to how we setup the API for the new refactored stats classes and @vantuyls question in #2617
