### ISSUE TITLE
The meaning of the glyphicon-share-alt icon in collection item lists is not immediately apparent

### ISSUE THREAD

**Issue by sandbergja** [samvera/hyrax#2648]
When a logged-in user views a collection landing page, small arrow icons appear next to certain items in the collection.  It turns out that this icon (generated on line 5 of https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/_show_document_list_row.html.erb) appears if that item was deposited by somebody else.  I can see why this would be useful, but I didn't understand the meaning of the icon until I actually looked at the code.

A simple step to make this more clear might be to include a tooltip to explain the meaning of that icon.

**Comment by RudyOnRails** [comment]
Hi @sandbergja. A screenshot would do (me) wonders, so I can get the same visual experience :) my organization is still on Sufia, but I participate in all of Samvera-land.

I like your thinking here. If it doesn't make sense, it's not doing its job.

**Comment by jcoyne** [comment]
This was introduced here: https://github.com/samvera/hyrax/commit/4abc9da1e918305f9e05a2a6af809015e4fcd345#diff-c03bd42c040adc7c0ff593ad84ceba42R9  Maybe @hectorcorrea or @mtribone  remembers something about why we do that?

**Comment by mtribone** [comment]
Holy mackerel that was almost 4 years ago!

Soo I'm thinking based on the code and the associated comments above the code, that instead of using the magic wand icon while the files were processing we switched to two other icons. The one with glyphicon-time representing "still processing" and the other "glyphicon-share-alt" representing "this is done processing."

I'm not sure that jives with @sandbergja's comments above or what it is actually doing now. I think it might be time to re-evaluate it and decide to improve it or delete it.

**Comment by mcdowney** [comment]
No longer relevant, closing
