### ISSUE TITLE
Search results have no dividing lines

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2680]
See nurax issues for comments: https://github.com/curationexperts/nurax/issues/158

Descriptive summary
The search results page has changed and I'm not sure if it's intentional or not. It does seem less readable with lots of whitespace and the loss of separating lines between results.

Before shot in 2.0:
![image](https://user-images.githubusercontent.com/4356335/36491987-14cc3422-16fa-11e8-8cfe-4ca6fe5152ed.png)

Now: 
![image](https://user-images.githubusercontent.com/4356335/36492006-1d060910-16fa-11e8-9436-6f65268836a2.png)

**Comment by elrayle** [comment]
@jrr @vantuyls @no-reply @jcoyne  This was a redesign based on the UI/UX mockups. The change was requested in issue https://github.com/samvera/hyrax/issues/1473

Additional discussion in nurax issue https://github.com/curationexperts/nurax/issues/158

@ggeisler Can you comment?

**Comment by ggeisler** [comment]
@julesies @elrayle Comparing before and after screenshots it doesn't look to me that there was a "loss of separating lines between results"; what was removed was the separating lines between metadata fields for each item. I don't know what mockup was used to make those changes, but in the closest mockup of mine that I can find (below) you'll see that I did include separating lines between results items:

<img width="642" alt="hyrax-mockups_graffle__results_-_collections_-_traditional_layout" src="https://user-images.githubusercontent.com/101482/36856070-5dc5864a-1d32-11e8-9945-e01bb0f920d8.png">

Feel free to make whatever changes you want, but in my opinion including separation lines between results, rather than between metadata fields, is sufficient to distinguish results. That's all Blacklight does, for example. 

I also think the "before" screenshot appears to separate result items better because it happens to include items that have longer titles, which help to serve as a more clear separator between items, as well as longer metadata values. So that's partly why the "now" screenshot has more whitespace (although whitespace is generally considered to be an aid to readability, so I'm not sure more whitespace is a bad thing).  

Finally, I'd also suggest the metadata fields in the current version are too close together, vertically (compare with my mockup above). They could probably use about 6 - 10px of additional padding between them. And, in my opinion, the size of the icons/thumbnails for each result item is too large (vertically).

**Comment by julesies** [comment]
@ggeisler you can see here better that there are no longer separating between search results. 

https://nurax.curationexperts.com/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=

**Comment by ggeisler** [comment]
@julesies Sure, thanks, but my point is I don't think I suggested there not be any separating lines between result items. @elrayle implied that your "now" layout is based on my mockups, but I cannot find any mockup I've done that doesn't include the separation line between result items. My mockups also don't show the metadata fields to be so cramped vertically. So to me this is an implementation issue, not a design issue. I had no involvement in the implementation of my designs. All I can offer is that you all consider the suggestions I made in my previous comment.

**Comment by julesies** [comment]
@ggeisler ah okay! We were assuming this changed was unintentional and not based on mockups as there was not a PR that addressed this view. 
It's good and helpful to have this mockup for the fix. thanks for giving feedback on why the view is off. Much easier now to hand off to a dev with your suggestions above in addition to adding a line between results.

**Comment by julesies** [comment]
@elrayle ☝️

**Comment by elrayle** [comment]
The same mockup was used for the refactor, but it appears that a few things got missed.

To summarize from @ggeisler, it looks like the following work remains...
- [ ] add separating lines between results (not between metadata fields)
- [ ] add a bit more spacing between the metadata fields
- [ ] change text 'Limit your search' to 'FILTER RESULTS BY'
- [ ] change text 'Clear filters' to 'Start Over' (visible when filters applied)

**Comment by ggeisler** [comment]
@elrayle I'd suggest the last two of the items in your comment above are "optional" in that someone might want to make sure they are consistent with the current application UI in general. They are more minor updates and without being involved in the current application development I can't say whether they still make sense to change or not.

**Comment by adamjarling** [comment]
@ggeisler Hey, I'm working on this now, and the wireframe above is super helpful.  For the metadata definition list titles ('Creator:', 'Date created:', etc.) should I stray from Bootstrap's `<dl>` styling and make the labels lighter colored (greyish) and non-bold?

**Comment by adamjarling** [comment]
or standard:

![search-results-dl-alt](https://user-images.githubusercontent.com/3020266/36995498-d2747772-2079-11e8-9c7b-ce8e5e0670cc.png)

**Comment by ggeisler** [comment]
@adamjarling Either approach looks okay to me. Maybe the deciding factor is to be consistent with any existing pages that show metadata in a similar `<dl>` approach. I'm not familiar with the current state of the app but maybe being consistent with the Work show page metadata presentation, for example?

Sorry for the inconsistency but when doing wireframes for Samvera I was sometimes conflicted over making what I thought were visual design improvements versus being consistent with design I think could be improved.

**Comment by adamjarling** [comment]
@ggeisler No worries.  The current pattern for `<dl>` follows suit with Bootstrap default: bolded titles.  I like your design, seems cleaner, but perhaps a better approach would be to make this style pattern consistent across all the application's `<dl>`s at a later date.

**Comment by adamjarling** [comment]
@elrayle The text line in your checkbox list above "change text 'Limit your search' to 'FILTER RESULTS BY'" I think is coming from Blacklight.  Do we want to pull in the Blacklight view/partial and override it in Hyrax?

**Comment by elrayle** [comment]
Not at this point.  We'll wait for another round of UI/UX analysis and recommendations.
