### ISSUE TITLE
Verification steps fails for non-existing users while sharing access to the collection

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2756]
Descriptive summary
Browser: Chrome 64.0.3282.140
OS: Windows 10
Use Case Number: CS_1.1
Issue: If the user tries to add a non-existing user in any of the Manager/Depositor/Viewer roles to share the collection, the system fails to recognize that the user is not present and adds the user ID to that specific role

Expected behavior
If the user is not present in the system, there should be a message below the search box stating 'No matches found'

Steps to reproduce the behavior
Login to the nurax system and open a collection or create a new one.
Go to the Sharing tab of the collection.
In the Add user search box, enter a random user name/mail which is not present in the system.
Select a role for that user and click on Add button.
The user name/mail though not present in the system gets updated in that respective role.

![image](https://user-images.githubusercontent.com/4356335/36923425-45d06944-1e39-11e8-8aee-298e2fe16481.png)

**Comment by elrayle** [comment]
Hmmm, this was fixed a little while ago.  PR #2611 for Issue #2578.  Something must have overwritten the fix.

**Comment by elrayle** [comment]
I did a little sleuthing on this one and narrowed it down to a PR where it worked before but not after.

Works after PR #2699 was merged on 2/23.
Does not work after PR #2692 was merged on 2/26.

I did a diff between the two PRs and nothing in PR #2692 looks like it would effect this functionality.  

I also did a diff of all files changes by PR #2611 with current master and there are no changes to the code committed by this PR.

**Comment by jgondron** [comment]
I can’t really say with any certainty just by looking at the changes, but my hunch is this id change https://github.com/samvera/hyrax/pull/2692/files#diff-78a0e78e96bec0ef65a05537850c198fL1 since this is how it finds the participant tab under it https://github.com/samvera/hyrax/blob/51b45cc2dc35eb8101f3eec5bde28922b63a0872/app/assets/javascripts/hyrax/app.js.erb#L49 -> https://github.com/samvera/hyrax/pull/2611/files#diff-1b54019ab65a5460f9134217b7bc42daR14
