### ISSUE TITLE
Long Collection Titles Overflow in Facet Dropdown Menu

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#2793]
### Descriptive summary

Long titles of collections and administrative sets overflow in the facet drop down menu.

### Expected behavior

Facet options should be contained within facet menu:
![image](https://user-images.githubusercontent.com/24395592/36285889-f497a64a-1272-11e8-9ecb-57f04d8db115.png)

### Actual behavior

User:
![image](https://user-images.githubusercontent.com/24395592/36285743-76af9382-1272-11e8-98b3-cd4e4d6487e8.png)

Dev Tools:
![image](https://user-images.githubusercontent.com/24395592/36285835-ca935286-1272-11e8-85c0-9c27cd5ebae0.png)

### Steps to reproduce the behavior

1.  Repository contents > Works
2. Filter works by collection

### Related work

moved from https://github.com/curationexperts/nurax/issues/177

**Comment by adamjarling** [comment]
@chrisdaaz Guessing this is using a plugin for the dropdown UI.  The easy solution would be just 'cut off' the text from overflowing past the selection.  Is that ok?  Getting the text to wrap might be more difficult as you might be getting into the plugin's styles.

**Comment by chrisdaaz** [comment]
@adamjarling what adjusting the width of the drop-down.

it starts to look better by tripling it:

![image](https://user-images.githubusercontent.com/24395592/38096729-3765b200-3339-11e8-807b-0861e86bb469.png)

i don't know what the optimal width would be because it affects the other fields too:

![image](https://user-images.githubusercontent.com/24395592/38096793-5f4b352e-3339-11e8-978a-7882ef3d0ef9.png)

![image](https://user-images.githubusercontent.com/24395592/38096821-73d5077c-3339-11e8-88d0-d35fa96caea2.png)

@samvera/hyrax-ui-ux-advisors

**Comment by mtribone** [comment]
@chrisdaaz Yeah I'm with @adamjarling on the truncating the long collection names and perhaps using an ellipses at the end. Otherwise you get into word wrapping and then the dropdown gets really long vertically. Perhaps filtering by collections in this manner isn't ideal if a) they are wordy b) there are a lot of them?

**Comment by elrayle** [comment]
@mtribone @ggeisler @adamjarling From the notes in this issue, I am seeing consensus in the approach to truncate the title and add ellipses.  Please give thumbs up on this and I will work on getting someone to fix this issue.

**Comment by adamjarling** [comment]
@elrayle I'll pick this up.  I think the best approach will be to try @ggeisler 's suggestion and truncate on the Rails end, as `<select> <option>` might not pick up the standard CSS "ellipsis" style.  And I also think best to let the dropdown menu stay dynamic width instead of fixed.

If we provide a Rails title truncation for this piece of UI, cap it at 7-8 words?   I'll play with it and see what seems reasonable...

**Comment by adamjarling** [comment]
@elrayle In the local dev environment, how do I get the "Collections" dropdown to appear in the "Filter Works" section of the Works page?   I see "Admin Sets", but not "Collections"...
