### ISSUE TITLE
Proxy bug - 'on behalf of' dialogue when editing a work.

### ISSUE THREAD

**Issue by newmanld** [samvera/hyrax#2822]
### Descriptive summary

If you are someone's proxy, two areas of potential confusion when editing a work, could be termed bugs, seen on Nurax.curationexperts.com on Hyrax Branch: v2.1.0_beta1b_qa.  Both areas deserve more testing.

When editing a work previously submitted on behalf of yourself, the 'on behalf of' dialogue appears, and you can change to the grantor instead of yourself.  This change does not seem to have an effect - it does not transfer ownership or change permissions, but after you save the edit, the 'on behalf of' drop down will be limited to the grantor, and you cannot change the choice back to yourself.

If you are a proxy for more than one grantor, when editing a work you submitted on behalf of grantor1, you will see in the drop down both grantor1 and grantor2.  If you change to grantor2, permissions and ownership are not changed, but this choice is remembered.  You can change back to grantor2 if you re-edit the work.

If you are a proxy for only one grantor, when editing a work you submitted on behalf of that grantor, you see only one choice in the drop down below 'on behalf of'.  This seems the expected behavior.

### Rationale

Users may see this dialogue and think they are transferring ownership when they are not, and instead should use the transfer ownership function on the dashboard.  (One proxy submitter did report this confusion in our local implementation of Hyrax 1.x.) 

### Expected behavior
The 'on behalf of' dialogue only appears when submitting a work and not when editing a work, or it is limited to the choice made previously when the work was submitted.  

### Actual behavior
Irrelevant choices are presented if you edit a work submitted on behalf of yourself, or if you are a proxy for more than one person.

### Steps to reproduce the behavior

1. Create two user accounts and make one user the other user's proxy.
1. Logged in as the proxy, submit one work on behalf of yourself, and one work on behalf of the grantor.
1. Still logged in as the proxy, edit both works and compare the choices in the 'on behalf of' drop down.  
1. Still logged in as the proxy, edit the work you submitted on behalf of yourself, and change to the grantor in the 'on behalf of' dialogue.  Save the work.  Look to see if permissions and ownership have changed.  Edit the work again, and see if you can change the drop-down back to yourself.
1. Add a third user account.  Make the same proxy the third user's proxy.   Log in as the proxy, edit each work, and compare choices in the 'on behalf of' drop down list.  Make changes in this list, save the work, and see if permissions and ownership changes, and what is remembered when you re-edit works.

**Comment by rjkati** [comment]
This is still present in hyrax 3.0.1. 

After changing the ownership of the work to the grantor as described in Step 4 above, I cannot change ownership back to the proxy because "Yourself" no longer appears in the "On Behalf Of" drop down menu on the Edit page. However, the proxy is still listed as the depositor on the file set and work. The grantor does not appear on either the file set or work.

When I add a third proxy, as described in Step 5, I can ownership between both grantor accounts, but am unable to reassign ownership to the proxy account, although the proxy account was the original depositor.

**Comment by jlhardes** [comment]
This doesn't appear to be a bug since being a proxy user for someone else means you are the owner for that work and can change ownership to that person you were doing things on behalf of and then you are no longer the owner. The history of you as the depositor would still be on the work so that makes sense as well.

There are 2 sections of documentation updates that might help here: Depositing as a Proxy and Transferring a Work in https://docs.google.com/document/d/1mgQCUXSay7OGjm_IiQwWjn1bWnMhaz0H3P_h4sBjI8I/edit that might help or might show that more clarification is needed to explain what is happening here.

**Comment by rjkati** [comment]
PR with update to documentation to address this issue: https://github.com/samvera/samvera.github.io/pull/434

There is also information in the feature guide for 2.1 that addresses this issue: https://samvera.github.io/create-works-2.1.html See "Depositing as a Proxy" at the bottom of the page.

**Comment by jlhardes** [comment]
Documentation to clarify proxies for Hyrax 3.x available at https://samvera.github.io/manage-proxies-3.x.html
