### ISSUE TITLE
Update Text on Collection Types

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2836]
### Descriptive summary

I have had a few questions about Collection Types from repo-managers and wanted to propose some interface changes to see if they help clear things up.  

Trying to achieve a few things here: 
-explains that there are 2 types included that you can't modify
-explains that these are repo-wide settings
-keep it really brief

In addition, I'd like to suggest removing the Examples, but instead link to github.samvera.io CE documentation (yet to be published) that contains examples and a lot more information we'd want to communicate to repo-managers when setting these up.

Proposed change: Suggest that "More about Collection Types" links to samvera.github.io docu
![screen shot 2018-03-23 at 2 24 09 pm](https://user-images.githubusercontent.com/4356335/37847063-f02fd0c4-2ea5-11e8-9fb6-464cfba88dd4.png)

Current text: 
![screen shot 2018-03-23 at 2 25 29 pm](https://user-images.githubusercontent.com/4356335/37847113-1794eadc-2ea6-11e8-84ca-7516e50b0a15.png)

**Comment by julesies** [comment]
@ggeisler @elrayle ☝️ thoughts?

**Comment by ggeisler** [comment]
@julesies I have no objection to your proposal, and I do think if there's agreement that significantly more information would be useful to provide it should probably be in a separate location rather than added to the expanded section. 

Another option (I'm not arguing either way, though) would be to add the link you're suggesting as a new line after the bulleted list in the expanded section. That way there is still immediate info available for users that might be too reluctant/lazy to click a link to view information that is not part of the app.

It might also be good to get some additional people who might have ideas about how real users will react to this page to weigh in, such as those on the original CE Requirements WG (e.g., @hannahfrost, @newmanld, @njaffer).

**Comment by julesies** [comment]
Great thanks! More context re: examples: One question I received about the examples was "What is the difference b/c user collections and exhibits?". It didn't seem to be clear that these were examples, maybe b/c it's a mix of collections that exist and don't? Like User Collections is a type that is included already... 

let me know what y'all think!

**Comment by ggeisler** [comment]
> It didn't seem to be clear that these were examples, maybe b/c it's a mix of collections that exist and don't? Like User Collections is a type that is included already...

Good point.

**Comment by newmanld** [comment]
I like the proposal and also @ggeisler's tweak to add the link after the bulleted list, so that some information is provided here, but more information is provided on samvera.github.io.

**Comment by hannahfrost** [comment]
:+1:  Inline examples offer immediate help and can serve as a teaser to the more detailed documentation linked there.

**Comment by elrayle** [comment]
@julesies @vantuyls It's not clear to me whether we landed on...
OPTION 1: removing all examples AND adding a link to docs
OPTION 2: updating text of examples to make it more clear they are example AND adding a link to docs

**Comment by julesies** [comment]
I'm fine with either, but lean to OPTION 1! Then it's easy for us to update examples :)

**Comment by vantuyls** [comment]
agreed. Option 1.

**Comment by cam156** [comment]
@laritakr and I were working on this ticket this morning.  We noted that the examples are in multiple languages and the documentation is only in english: https://samvera.github.io/collection-types.html (assuming we have the correct link).

What do you want to do for other languages?

**Comment by laritakr** [comment]
Dependent on appropriate pages to be created on samvera.github.io

**Comment by elrayle** [comment]
Agree with @cam156 that https://samvera.github.io/collection-types.html is a good option for 2.1.0.  I understand from @julesies that it is desirable to have a manager oriented page in the manager section instead of the dev section of the documentation, but that can wait until 2.1.1.

@julesies @vantuyls Do you concur?

**Comment by no-reply** [comment]
Is this ticket still live?
