### ISSUE TITLE
Add Home as the first breadcrumb for all pages

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2848]
### Descriptive summary

For all pages in Hyrax that have breadcrumbs, should have Home as the first breadcrumb.  The Dashboard pages already have this.  The public facing repository object pages do not, and need to.

### Rationale

Make breadcrumbs consistent.

### Expected behavior

The first breadcrumb to be Home

### Actual behavior

In some pages, the first breadcrumb is not Home

### Steps to reproduce the behavior

As an admin and then again as a non-admin...

1. Visit the following pages and confirm the breadcrumbs start with Home.

Dashboard -> Collections -> click a title to go to admin show page
Dashboard -> Collections -> click a title -> click Public view of Collection

Dashboard -> Works -> click a title to go to show page
Dashboard -> Works -> click a title -> Analytics

Dashboard -> Works -> click title (for a work that has files) -> click title for a file
Dashboard -> Works -> click title (for a work that has files) -> click title for a file -> Edit This File
Dashboard -> Works -> click title (for a work that has files) -> click title for a file -> Analytics

### Related work

[Breadcrumb related issues](https://github.com/samvera/hyrax/issues?q=is%3Aissue+is%3Aopen+label%3Abreadcrumbs)
Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
I'm not sure that I agree with that.  The logo in the top left is already a link to the home page.  Adding a "Home" link will just add clutter to the page and make it less usable. cc @ggeisler

**Comment by ggeisler** [comment]
I'd go with adding the "Home" link as suggested in the ticket description. While the logo **is** a link to home, having a more explicit link can be helpful (the logo being linked to home is not necessarily obvious to all users, while a link that says "Home" is pretty clear and unambiguous) and given how short it is, I don't think adds much clutter. 

Also, one could argue that having all breadcrumbs start with the same "Home" link provides a consistent anchor for the user that actually reduces clutter (because all breadcrumbs start in a consistent and reliable way) and potential disorientation (not that I think the app is so complicated that disorientation is likely to be a frequent problem).

**Comment by vantuyls** [comment]
i'm with gary and lynette on this. 

also note - the logo currently sits in a place that commonly (?) interferes with branding guidelines for the institution. see:
https://searchworks.stanford.edu/databases
http://small.library.virginia.edu/

logos in these instances often are required to link back to either the institutional homepage or to the sub-unit homepage (e.g. the library), so that logo as a consistent placeholder of "take me back to the homepage of this repository" is not always reliable.

**Comment by jcoyne** [comment]
Okay. Sounds good.
