### ISSUE TITLE
Handle sorting of  records without a value for 'date_uploaded'

### ISSUE THREAD

**Issue by afred** [samvera/hyrax#2957]
### Descriptive summary

PR #2813 makes "recently uploaded" sort on the `date_uploaded_dtsi` rather than the `system_create_dtsi`. However, it doesn't address how to sort items that don't have a value for the `date_uploaded_dtsi` field.

### Rationale

During a code review, we wanted to merge PR #2813 on the condition that a ticket was made to handle sorting in the absence of a value for `date_uploaded_dtsi`.

### Expected behavior

Don't know yet. Should records without a value for `date_uploaded_dtsi` be sorted at the end? Should sorting fall back to `system_create_dtsi`?

**Comment by no-reply** [comment]
this is backlogged because `date_uploaded` is Hyrax core metadata. in general, the system counts on it being present.

`system_create_dtsi` is populated from fcrepo and is backend dependent, we shouldn't count on this being present.

since this has been open in this state for almost 3 years now, i'm closing it off.
