### ISSUE TITLE
Private works minimally visible to all users by url if pending review

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hyrax#3104]
### Descriptive summary

When a work is created with the one-step mediated workflow a non-authorized user is able to access a minimal view of the work by url.  The work is not searchable.  Once the work has been approved then the user is prompted with a login.  This is a small security hole which leaks the work's existence, title, type, and status.

### Expected behavior
Unauthorized users should never be able to see any information about items that are private.

### Actual behavior
Unauthorized users can see minimal information about the item while it is pending review.

### Steps to reproduce the behavior

1. Create a private work with the one-step mediated deposit workflow, but don’t approve it.
1. In an incognito window, navigate to the url of the new un-approved work.  You can see some limited information including title.
1. Approve the work
1. In the incognito window, refresh and you’ll be prompted to login.

**Comment by kdid** [comment]
What is the desired behavior here?

We are landing here because the work is still in workflow - regardless of whether the work is public/private, etc..

I'm inclined to think that you should not be able to view any information about a Public work either, until it has completed the workflow process. (The info is not final - it may be wrong, visibility could even be wrong, or just not ready for public consumption, etc..) In that case if you landed on this page, for any work still not approved, public/private you'd see "The work is not currently available because it has not yet completed the approval process" - and no additional info about the work at all.

Or is the desire here that you should be presented with an unauthorized/login page for a non-public, unapproved work and then be able to see the limited information?

**Comment by vantuyls** [comment]
I think the desired behavior is that if your role in the system (admin, etc.) allows you to see the content, then you can, but if your role does not, then the item should not be visible, even minimally.

**Comment by chrisdaaz** [comment]
@kdid i think the unauthorized/login page makes sense for this.
