### ISSUE TITLE
Limit dc:title to only occur once

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3299]
### Descriptive summary

Require dc:title but limit its use to once with dc:alternative being used for additional titles.

### Rationale

Right now, dc:title may be used multiple times in Hyrax. Since there is no modification to add data about the language (which would be a good reason to repeat title) or control ordering, this may lead to confusion about the authoritative title. Limit dc:title to be used {1} times. Prefer dc:alternative for other forms of the title.

Right now this seems to be managed with: https://github.com/samvera/hyrax/blob/2.0-stable/app/models/concerns/hyrax/core_metadata.rb#L16-L18 but we were unsure if there's anyway for the metadata worker to engage with that.

**Comment by geekscruff** [comment]
There are two approaches to this:

1) leave the underlying property as 'multiple' and limit to a single title in the form
2) change the underlying property

2) is a bigger architectural change, and would need changes across the application (wherever title is accessed as an array, it would need to be accessed as a string). It would also be a breaking change as any multiple titles would disappear, so it would need a migration utility. If this were the proposed approach we could do this in two stages by adding alt_title into a release with a utility to transfer any additional titles first, so that people can do data cleaning, then change title in a subsequent (major) release.

#1505 is similar in that it would be a breaking change, so could have a similar two stage approach

**Comment by no-reply** [comment]
> leave the underlying property as 'multiple' and limit to a single title in the form

in my opinion this is the only serious option. single valued properties do not exist at the data model level, defining ActiveFedora/ActiveTriples properties that pretend they do (rather than validate on input/output) is extremely error prone, and risks data loss.

**Comment by ruthtillman** [comment]
That also leaves space for the eventual support for multiple languages

**Comment by dlim87** [comment]
QA - Title is a required field, there is only one title field. In the metadata it is displayed as an array with a single value
