### ISSUE TITLE
No user feedback in case of disk failure

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3340]
### Descriptive summary

On hyrax (2.3.3).
We experimented a network failure resutling in NFS sharing problem. Fedora  could not write to the file system anymore. But users still thought they could add files: no errors would appear until you tried to re-download a file.  Files were displayed in the file manager as present.
The async process error was only visible in logs :
`E, [2018-10-18T16:28:11.237271 #29904] ERROR -- : [ActiveJob] [IngestJob] [30a8c066-f8cf-4a8a-b8b0-43dce7b14e90] Error performing IngestJob (Job ID: 30a8c066-f8cf-4a8a-b8b0-43dce7b14e90) from Async(default) in 4164.51ms: Ldp::HttpError (STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: Unable to create directory /home/fedora-data/fcrepo.binary.directory/0e/08/6d required to store 0e086dd52a71a5ee165cc0c8d545994481a81bce in binary store`

### Rationale

When Fedora file ingestion async process fails, the end user should know that his failed was not saved.

### Expected behavior

- A message is displayed for failure
- The file manager does not pretend to have the file

### Actual behavior

File ingestion fails silently in case of disk failure.

### Steps to reproduce the behavior

1. Put Fedora binary directory on the file system
2. Restrict unix permissions to prevent Fedora from writing (you simulate disk failure or disk full situation)
3. Create a new work and deposit files.

**Comment by no-reply** [comment]
It looks like you're using the `:async` adapter, which we'd recommend you not do in production.

A production-ready `ActiveJob` handler (e.g. `sidekiq`) will provide you a way to manage and correct errors in jobs as an administrative/systems task. For example, a robust production setup might report uncaught exceptions to [Honeybadger](https://www.honeybadger.io/), and put failed jobs into a retry cycle. The fix for the issue you describe would be to observe the error, correct the permissions on the filesystem, and allow the jobs to retry in the new environment.

Proposals about how to usefully expose job progress information to users are welcome, so long as they are compatible with these kinds of best-practice `ActiveJob` production approaches.

**Comment by j-dornbusch** [comment]
Thanks for your help. Since we intend to use Sidekiq on the production instance, we can avoid the problem by applying your recommendations.
