### ISSUE TITLE
Admin Set and Collection participants tab layouts are inconsistent

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hyrax#3365]
### Descriptive summary

Remove buttons for collection participants are not consistent between the disabled "Repository Managers" and user added users and groups.  Note how the disabled one is missing the padding.

<img width="802" alt="screen shot 2018-11-01 at 10 55 14 am" src="https://user-images.githubusercontent.com/1053603/47864862-0a915480-ddd1-11e8-8b5e-fdc1b432f23d.png">

It looks like this CSS is to blame: https://github.com/samvera/hyrax/blob/master/app/assets/stylesheets/hyrax/_file-listing.scss#L100-L104

**Comment by adamjarling** [comment]
@cjcolvar I'm updating the scope of this ticket a bit to address what I think is the underlying issue.  In the collection extensions sprint, we re-factored the Participants tab layout for a Collection, but these didn't carry through to the Admin Set Participants tab view.   Seems that they should probably be using the same view partial since so much of the markup is the same, but will save that for another time.   Updating the layout, should fix the button issue, and more.

![admin-set-participants-tab](https://user-images.githubusercontent.com/3020266/47867380-53e0a480-ddcf-11e8-8718-112b494918f5.png)

![collections-participants-tab](https://user-images.githubusercontent.com/3020266/47867379-53e0a480-ddcf-11e8-9a3c-c9d7182cbc26.png)
