### ISSUE TITLE
Switching language resubmits page discarding any un-saved edits

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3414]
### Descriptive summary

Switching language resubmits page discarding any un-saved edits. This occurs on any page with edit forms.

### Expected behavior
Switching language on an edit page with edits should preserve the edits.

### Actual behavior
Page is resubmitted with new language and edits are lost.

#### radio button 
1. https://nurax-dev.curationexperts.com/batch_uploads/new?locale=en
2. check "Public" radio button (don't save) 
3. switch language to Deutsch 
4. selection is reset to "Private" radio button 

#### tab
1.  https://nurax-dev.curationexperts.com/dashboard/my/collections?locale=en
2. switch language to Deutsch 
3. select "Ihre Sammlungen: tab
4. switch language to English

### Related work

Link to related tickets or prior related work here.

**Comment by fritzfreiheit** [comment]
This turns out to be a more general problem. When a new language is selected, the current page is resubmitted with a new language ( i.e. [https://nurax-dev.curationexperts.com/batch_uploads/new?locale=en](https://nurax-dev.curationexperts.com/batch_uploads/new?locale=en) --> [https://nurax-dev.curationexperts.com/batch_uploads/new?locale=de](https://nurax-dev.curationexperts.com/batch_uploads/new?locale=de) ) which refreshes the page throwing away any edits without saving.

**Comment by fritzfreiheit** [comment]
After discussion during the sprint stand up for 3.0.0 release sprint on 2019/06/12, it was decided to update this issue to reflect larger problem (see my immediately prior comment) remove this issue from the sprint for later consideration.

**Comment by mcdowney** [comment]
Closing as this is represented by the larger issue mentioned above and referenced in #3978
