### ISSUE TITLE
uv fails rendering png with transparent alpha channel 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3422]
### Descriptive summary

Universal viewer (uv) fails rendering png with transparent alpha channel as well as uv download is providing corrupt jpg version 

### Expected behavior
uv should provide original png download link and render (if needed) jpg correctly

### Actual behavior
https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99

### Steps to reproduce the behavior

1. https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99Do this

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
Someone is going to need to look into this to determine if this is a UV issue, a RIIIF issue, a Hyrax issue, or some combination. After that analysis, we'll probably need to scope a ticket for Hyrax-side handling.

**Comment by geekscruff** [comment]
I've confirmed that this is a problem with RIIIF and `convert`.

**Comment by dlim87** [comment]
The UV isn't working for me in general, it's just rendering a black box for all the works I opened. In safari, chrome, and firefox

**Comment by dlim87** [comment]
@dlpierce ^

**Comment by dlpierce** [comment]
@dlim87 Did you regenerate the test app or update the iiif_image_builder lambda like this: https://github.com/samvera/hyrax/pull/3760#discussion_r312195728

**Comment by dlim87** [comment]
I kinda dropped the ball on following up with this, since I was trying to check up on it through nurax. @dlpierce would further action need to be done on nurax as per that previous comment? ^

Unlike the past month, the UV is actually rendering now; but unfortunately, it's exhibiting the same problem as this ticket was created to address: it's displaying (and downloading) a malformed jpeg version, instead of the png version with the proper transparency layers.

**Comment by MariaStarPower** [comment]
**Fail** - the Universal Viewer is not rendering anything.

![image](https://user-images.githubusercontent.com/32848057/101082656-a5d0f700-3560-11eb-901e-a083bb55f373.png)

![image](https://user-images.githubusercontent.com/32848057/101082710-bc774e00-3560-11eb-9546-2b80e3ee3c27.png)

**Comment by mark-dce** [comment]
The server appears to be configured to use RIIIF.  It looks like the problem is that image URLs embedded in the manifests are not using encrypted HTTP (i.e. they say `http://nurax-dev...' and need to say `https://nurax-dev...)

Sample work above: https://nurax-dev.curationexperts.com/concern/images/hd76s024f

**Comment by mark-dce** [comment]
Sample work: https://nurax-dev.curationexperts.com/concern/images/hd76s024f
Manifest for that work: https://nurax-dev.curationexperts.com/concern/images/hd76s024f/manifest.json
First image referenced in that manifest: http://nurax-dev.curationexperts.com/images/9k41zd63m%2Ffiles%2Fc78f093e-f46e-4f0a-b7ea-c3944f162bf8%2Ffcr:versions%2Fversion1/full/600,/0/default.jpg <-- this fails because the server is configured not to respond to http and isn't issuing the necessary redirect to https
Same link with HTTPS: https://nurax-dev.curationexperts.com/images/9k41zd63m%2Ffiles%2Fc78f093e-f46e-4f0a-b7ea-c3944f162bf8%2Ffcr:versions%2Fversion1/full/600,/0/default.jpg <-- this works

**Comment by mark-dce** [comment]
I'm not familiar with RIIIF or the hyrax manifest building service anymore to know where to make the switch from embedding https links in the manifest instead of http.  If it's in the ruby code, you should be able to make an update and things might sort themselves out.

**Comment by mark-dce** [comment]
If the configuration needs to be made in the server .env.production file, let me know and I can make that change.

**Comment by jlhardes** [comment]
This example is now loading in Universal Viewer on nurax-dev but png seems to still be rendering incorrectly in the viewer and jpg for download is still corrupted.

**Comment by jmfrenzel** [comment]
Fix for transparent alpha-channel was published with  riii v2.1.0 see https://github.com/samvera/hyrax/pull/3760

From nurax's github repo riii v2.0.0 is set Gemfile.lock is  https://github.com/curationexperts/nurax/blob/8cd456e25ce10f50828c0e4d97899ae3003bc14c/Gemfile.lock#L717

**Comment by no-reply** [comment]
i think it would be wise to regard this as fixed. i'm not sure there's value in repairing nurax beyond what @maxkadel did yesterday.
