### ISSUE TITLE
Work Form - Clicking Remove on First Required Input Stops the Input Being Required

### ISSUE THREAD

**Issue by orangewolf** [samvera/hyrax#3526]
### Descriptive summary

In Hyrax 2.3.3 and master (probably other versions) when editing a work, if you click remove by a required field the form validations are not updated.

Video: https://cl.ly/da318361419a

### Rationale

Hyrax server side validations for this form are not really used as we have Javascript client side validations.  That works well for required fields _unless_ the user clicks the remove link. 

### Expected behavior

No matter how a user clears or removes a required field, the field should still be required.

### Steps to reproduce the behavior

1. Go to edit an existing work
2. Click remove next to the first title field
3. Note that the field is no longer present, but the form is still submittable.

**Comment by blancoj** [comment]
@no-reply When items that can contain multiple values and are also required are drawn, they contain an attribute called required with a value required. - like this: `required='required'`.  The first row drawn contains this attribute, but the second row does **NOT**.  This is done because only one value needs to be entered, and if the second row contained this attribute, the user would be forced to enter two values.  If a user goes to edit an existing work that contains one value for a field that can have multiple values, and deletes the row containing the required attribute, the second row then becomes the only one shown on the page and it does not contain the required attribute.  The user can then save the work, leaving a required field without a value.  All this is handled in the hydra-editor gem.

One possible solution would be to not draw the second empty line automatically, but force the user to hit `Add` to get a new entry line.  I think that could solve the problem.  I think also that this would be a change in hydra-editor.

**Comment by no-reply** [comment]
> One possible solution would be to not draw the second empty line automatically, but force the user to hit Add to get a new entry line.

that's the behavior i see now, both in Nurax in my browser and in the attached video. How would this fix the issue?

**Comment by no-reply** [comment]
It sounds like we need to open an issue on Hydra Editor for this. Does that seem correct?

**Comment by rjkati** [comment]
Issue is still present in Hyrax 3.0 rc3

**Comment by jeremyf** [comment]
We have some logic for this in Sipity (ND app). The logic we applied was to say that the first element (and thus the required element) could not be removed.  I'm going to go down that path for a solution.

**Comment by jeremyf** [comment]
With the following CSS:

```css
.multi_value .listing li:first-of-type .remove { display: none; }
.multi_value .listing li:first-of-type { width: 83.333333%; }
```

I get the following UI:

<img width="606" alt="Screen Shot 2021-02-03 at 4 49 12 PM" src="https://user-images.githubusercontent.com/2130/106814035-c8a28900-663f-11eb-8d33-fc9b1d641de7.png">

I spent some time working through the javascript, and it's a rather nasty labyrinth.  First, all multi-values are written by JS (see the [field_manager.es6 file in Hydra::Editor](https://github.com/samvera/hydra-editor/blob/b0d0eee963ebff8d5769b7e535542ab48f252c07/app/assets/javascripts/hydra-editor/field_manager.es6#L1)).  My hope was to be able to discard the "X Remove" button from the HTML of the first element.  However, that proved difficult as there's an assumption that that HTML will be around when we click the "Add another Title" link.

It would be possible to "store that" somewhere, but that felt like some complicated changes.  Instead I went down the path of CSS and settled on the above.  It's not quite perfect but it does things a little better.  Yes, you could disable stylesheets and thus see the button again. Yes you could inspect element and do nefarious things.  But at the root, this solution preserves the "required" input field AND helps avoid POSTing the form.

I'm submitting a PR to Hydra::Editor

**Comment by jlhardes** [comment]
This is working for me as @jeremyf describes and stops the reported issue from happening. This is fixed.
