### ISSUE TITLE
Allow admin users to share works with groups they aren't members of

### ISSUE THREAD

**Issue by svanschuyver** [samvera/hyrax#3534]
### Descriptive summary

Hyrax Version: 2.4.1

### Rationale

Admin users (and potentially other users) may need to assign permissions to groups that they are not a member of

### Expected behavior

The drop down box for groups on the 'Sharing' tab of the New Work page includes all groups in the system, at least for admin users

### Actual behavior

The drop down box for groups on the 'share' tab of the New Work page only shows the groups that the user is a member of

### Steps to reproduce the behavior

1. Log in
2. Navigate to the 'New Work' page
3. Click on the 'Sharing' tab
4. Select the drop down box next to 'Add group'
5. Only the groups you are a member of will be listed

### Related work

Link to related tickets or prior related work here.

**Comment by svanschuyver** [comment]
As a workaround, in the app/views/hyrax/base/_form_share.html.erb file, line 24, replace `current_user.groups` with `Role.pluck(:name) + ['registered']`

**Comment by dlim87** [comment]
I had to spin up a local instance because nurax only has an admin group, which an admin obviously belongs to. As of https://github.com/samvera/hyrax/commit/3b50a7631bee238003ae6d5416dfe22cd4589f3c, this is working. 

![Image 2019-11-06 at 8 54 40 AM](https://user-images.githubusercontent.com/5492162/68319693-92104400-0073-11ea-9720-ff433db282cb.png)

Steps taken
1. configured as per https://github.com/samvera/hyrax/wiki/Configuring-an-OS-X-Samvera-Dev-Environment#configuring-Hyrax, except using a _different_ username for the admin
2. the directions in the OP of this issue
