### ISSUE TITLE
Works::VirusScanner uses AF for logging

### ISSUE THREAD

**Issue by rotated8** [samvera/hyrax#3587]
### Code

lib/hydra/works/virus_scanner.rb

### Active Fedora

  calls `ActiveFedora::Base.logger&.warn(msg)`

### Related issues

**Comment by lsitu** [comment]
@no-reply What's the scope of this ticket? It looks like this need to be changed in hydra-works code base https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/virus_scanner.rb#L53 but not Hyrax, which seems like to be a wider swing issue since `ActiveFedora` is used there.
I see `ActiveFedora::Base.logger` is used in Hyrax (https://github.com/samvera/hyrax/blob/master/lib/hyrax.rb#L52) that may need to fix. Should we create another ticket for it? I think we can just use `Valkyie.logger` directly, or copy those logger codes from `ActiveFedora::Base`. Which way do you prefer?

**Comment by no-reply** [comment]
@lsitu i think the best thing to do may be to port `Hydra::Works::VirusScanner` into Hyrax directly. We're going to want to drop the `Hydra::Works` dependency from Hyrax eventually, and it seems like this could just be moved entirely.
