### ISSUE TITLE
When creating a Valkyrie::Resource from an ActiveFedora::Base, populate id and alternate_id with the same value

### ISSUE THREAD

**Issue by hackmastera** [samvera/hyrax#3643]
Put a test somewhere, probably on ModelTransformer or persister.

**Comment by revgum** [comment]
I'm recalling our sprint back in Penn State that a Valkyrie::Resource id (at least for postgres) had to be a UUID. In the case that ActiveFedora::Base, when they get id's that aren't UUID, wouldn't this cause a problem with enforcing that Valkyrie::Resource.id = ActiveFedora::Base.id

**Comment by hackmastera** [comment]
Okay it sounds like in @revgum's scenario a person is using 2 metadata adapters: 1 is maybe postgres and the other is wings. And this person wants to keep the 2 data stores in sync. So it sounds like ActiveFedora records need a place to store the valkyrie id. @no-reply, does this sound right to you?

**Comment by revgum** [comment]
@hackmastera @no-reply Ah.. I'm following the line of thought here now, I think.. With regard to wings, we can use non-UUID id's because the backend doesn't have the same requirement (as far as Postgres goes). My line of thought had to do with when we transition from Wings/AF to something else (potentially Postgres).

**Comment by revgum** [comment]
It appears this was initially covered in https://github.com/samvera/hyrax/commit/6fd63d2bd298764636d9383c3cab353f67ec1a65
