### ISSUE TITLE
wings persister spec: can save nested resources

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#3662]
- [ ] pass the shared Valkyrie specs related to resource nesting; or
  - [ ] document specific resource nesting behavior supported by Wings (e.g. write this up in the Hyrax Valkyrie Usage Guide)

**Comment by no-reply** [comment]
i'm reviving the issue because i've just marked the referenced test pending.

the original scope and fix for this issue was a specific test, and some hard-coding was introduced as a proof-of-concept. in the context of #3627, we need a more general solution that follows something more like the patterns for Resource/AF Model generation used for top-level models; this has matured a lot since the work on this ticket was originally done.

Re-scoping this now to:

  - [ ] pass the shared Valkyrie specs related to resource nesting; or
  - [ ] document specific resource nesting behavior supported by Wings (e.g. write this up in the Hyrax Valkyrie Usage Guide)

**Comment by hackartisan** [comment]
Hyrax does not have use cases around nested resources in the Valkyrie sense. closing for now as wontfix; if it turns out that fileset and file metadata modeling requires this feature we can reopen (see reference from #3940)
