### ISSUE TITLE
Enable GeoNames functionality for Location field in collections

### ISSUE THREAD

**Issue by simholt** [samvera/hyrax#3725]
### Descriptive summary
GeoNames is enabled on item description for Location but not for collections.

### Rationale
The Location field should function the same way for items and collections.
- - - -
### Expected behavior
Location should function in collection edit the same way it does at the item level:

![location_item](https://user-images.githubusercontent.com/33705514/55257372-ec633f80-521c-11e9-83b9-4cd1da1b522d.png)
- - - -
### Actual behavior
The user can type anything:

![whatever_you_want](https://user-images.githubusercontent.com/33705514/55257887-824b9a00-521e-11e9-9f23-04d952b8cc65.png)

### Steps to reproduce the behavior

1. Create a collection. 
2. Under Location, start typing.

**Comment by no-reply** [comment]
@samvera/hyrax-metadataists, @samvera/hyrax-repo-managers do any of you have feedback on this request?

There's a certain logic to the idea that the collections should use the same controlled vocab setup as the items, but it's not obvious to me that this is the current design. Should we move forward with alignment here?

**Comment by Dananji** [comment]
@no-reply I found this issue #3819, which I think is related to this one.

**Comment by geekscruff** [comment]
+1 for alignment

**Comment by jeremyf** [comment]
I believe aligning the the logic makes complete sense and removes surprises from the UI.

We welcome pull requests to bring these in alignment.

**Comment by rjkati** [comment]
Geonames is not enabled in the Location field for collections in Hyrax 3.0.2

**Comment by jlhardes** [comment]
Thanks @rjkati! This has been labeled as an enhancement and I can see that since it is adding a feature that hasn't been there before but I can also see how this could be viewed as a bug since the field isn't functioning in collections the way it already functions in works. I will keep it in the project board for now and consider it as a possible bug to correct. If the other location/geonames bugs are worked on soon (#1065 and #3269) this might fit in with that work.

**Comment by jlhardes** [comment]
This is working as expected on nurax-dev for collections!
