### ISSUE TITLE
setup solr indexers to use valkyrie/wings

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3800]
### Descriptive summary

Setup solr service and indexers in hyrax to use when persisting via valkyrie.  This will create and register a solr indexing adapter that can be used with any backend.  Wings uses ActiveFedora for solr indexing.  There will need to be some thought put into how the indexing adapter will be used when the metadata/storage adapters are configured to use Wings.  Once we move away from AF / wings, having an indexing adapter will allow new indexing adapters to be created for other indexing schemes (e.g. elastic search) that can be swapped out. 

#### Hyrax indexers

The various Hyrax indexers live in [app/indexers](https://github.com/samvera/hyrax/blob/master/app/indexers).

The valkyrie version of the indexers, at least for now, will live in [lib/wings/indexers](https://github.com/samvera/hyrax/blob/master/lib/wings/indexers).

### Creating Valkyrie indexers

REF: https://github.com/samvera/valkyrie/issues/598

Valkyrie does not currently have the concept of an indexing adapter, but there have been discussions about creating one (see issue https://github.com/samvera/valkyrie/issues/598).  The work being done in Hyrax will serve as a test case for this concept.

#### Key Concepts and Functionality:

* The indexer is write-only.  As such, it can create light weight solr docs including only the required metadata and can control additional information going into the solr doc to support relationships between objects.
* There is a chain of indexers that builds up the solr document.  See PR #3866 which adds a basic indexer and proposes indexers Hyrax::Indexers::WorkIndexer and Hyrax::Indexers::CollectionIndexer (see registration of indexers at [indexing_adapter_initializer.rb](https://github.com/samvera/hyrax/blob/master/config/initializers/indexing_adapter_initializer.rb#L11-L12)). The last to write to a field has the final say on the value of a particular field in the solr doc.
* The chain of indexers will also need to address the nested indexing functionality which creates the hierarchy of collections within the solr documents for each collection in the hierarchy.
* Indexing chains need to be customizable to allow apps to further control the creation of solr docs.  If a field should have a different name or be dropped from the index, an app can overwrite a provided indexer to modify the desired behavior.
* There needs to be a solr_read_service that supports the connections to solr required for reading documents since the indexer is write-only.
* Currently there are two solr cores set up:  1) active fedora core, 2) valkyrie core.  Need to write to both until all uses of the active fedora core are addressed, then the active fedora core can be removed.
* At some point, the active fedora indexing classes and methods will need to be deprecated pointing to the new Valkyrie approach as the replacement.  Not clear exactly how this will unfold since Wings uses ActiveFedora which writes to both Fedora and Solr as part of the persistence process.  I don't know if it is possible to stop ActiveFedora from writing to Solr, which would be desirable once the Valkyrie indexing process is complete.

#### Next steps 

At this writing, the next step is the creation of Hyrax::Indexers::WorkIndexer and Hyrax::Indexers::CollectionIndexer.  Register in [indexing_adapter_initializer.rb](https://github.com/samvera/hyrax/blob/master/config/initializers/indexing_adapter_initializer.rb#L11-L12)

#### Additional features to consider

* Indexing has been expensive in the past. Can we reenvision indexing to do partial document updates to avoid full reindexing which includes the nested indexing?
* When should commit occur?  Currently on a single document basis.  Would the long term ideal be to use autocommit which designates a buffer size and/or time period when exceeded will trigger a commit?  Some sites want to control when the indexing fully commits to solr, especially in the case of batch processing for edit/import.

### Considerations

* The current indexers in master cannot be removed until the valkyrie work on indexing and solr are fully complete.  Putting the indexers in the `lib/wings/indexers` directory may be useful to allow the work to proceed side-by-side the current implementation.
* There are other solr related issues that have this issue as a prerequisite. 
* We don't intend to use Valkyrie's solr metadata adapter as it is a full resource read/write adapter.  This could cause unwanted object bloat and skew search results.  See comments in Valkyrie Issue https://github.com/samvera/valkyrie/issues/598#issuecomment-503162347 for a discussion on this topic.

### Related Work

A good bit of the initial setup work for the indexer is complete.  See these Issues and PRs for related discussions and initial code. 

* Hyrax Issue #3800 setup solr indexers to use valkyrie/wings
* https://github.com/samvera/valkyrie/issues/598 Consider adding an "Indexer” concept
* Hyrax PR #3834 [wings] Inline #query, #post, and #get into solr_service from AF
* Hyrax PR #3837 [wings] Start building out a Valkyrie::IndexingAdapter
* Hyrax PR #3854 Add save to the valkyrie solr indexing adapter
* Hyrax PR #3857 [wings] Add switch to use valkyrie in the solr service
* Hyrax PR #3859 [wings] Add save_all, delete, and wipe! to solr indexing adapter
* Hyrax PR #3866 [wings] Migrate initial indexing hash to base indexer
* Hyrax Issue #3863 Deprecate feature to configure indexing for a property when defined in model
* https://github.com/samvera/valkyrie/issues/599 add scope to indexers
* Valkyrie code: [lib/valkyrie/persistence/solr/composite_indexer.rb](https://github.com/samvera/valkyrie/blob/master/lib/valkyrie/persistence/solr/composite_indexer.rb)

### Discussions

[2019-08-08 Current Status of Indexing Effort](https://docs.google.com/document/d/1Eyu_C-eoJK6KdugxoETVoPb2q9fVWSDUop0qMS-udWo/edit?usp=sharing)

**Comment by revgum** [comment]
**Considerations**
- There are multiple classes that have ties to ActiveFedora (not limited to, but including: Hyrax::WorkIndexer, Hyrax::FileSetIndexer, Hyrax::BasicMetadataIndexer)
- [Hyrax work indexer generator](https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/work/templates/indexer.rb.erb) has built code for users of hyrax that has a dependency on `Hyrax::WorkIndexer` which seems like it might be a good place to start for targeting an abstraction to handle AF vs. Valkyrie.
- Since indexers are oriented toward Solr documents, there shouldn't be a need for massive overhauling of the `#generate_solr_document` methods

**A proposed path forward**
- [ ] Crib previous [Hyrax Valkyrie Indexers](https://github.com/samvera/hyrax/tree/valkyrie-6/app/indexers/hyrax) into `wings/indexers`
- [ ] Build a new Hyrax `indexing_service` configuration that defaults to `ActiveFedora::IndexingService`, allowing for a Wings override.
- [ ] Replace `ActiveFedora::IndexingService` class inheritance with `Hyrax.config.indexing_service` configuration
- [ ] Build a `Wings::IndexingService` which facilitates including cribbed, and any additionally needed valkyrie indexers, as well as setting metadata previously handled by AF::IndexingService (https://github.com/samvera/active_fedora/blob/master/lib/active_fedora/indexing_service.rb#L33-L45)

**Comment by hackmastera** [comment]
We need a place to put field-by-field indexing information for valkyrie, because it can't go in the valkyrie model. Maybe we can provide a migration that will move the `index.as` stuff from models into indexers?

**Comment by hackmastera** [comment]
As per discussion with @no-reply:

The wings persister we have in place already indexes due to the fact that it saves via AF. If we interact with solr via the fields we expect to find there, we should generally be fine. Other tickets exist for wrapping AF / SolrService behavior in various ways, which we should be able to move forward on step-wise.

In general we've agreed to move away from solrizer-style field name abstractions.

Near-term, we'll deprecate use of `ActiveFedora::IndexingService` by introducing `Hyrax::IndexingService` which initially inherits from AF. (see https://github.com/samvera/hyrax/commit/c0d7d195dc8856756bb0a448eae1314ee517804d)

The next step will be to build up a solr indexing service in hyrax directly, to some extent as research in service of https://github.com/samvera/valkyrie/issues/598.

Once we have a sense of what we'll be moving toward, we can deprecate the practice of providing indexing behavior during property definition in models.

**Comment by elrayle** [comment]
@hackmastera @no-reply I'm pretty sure this issue is fixed by Hyrax.index_adapter and Hyrax::SolrService.  Would you agree?  If so, feel free to go ahead and close this.

**Comment by no-reply** [comment]
agreed. i think we have a nice pattern for this, and anything more specific should be written up more specifically.
