### ISSUE TITLE
Work is not visible to owner in a mediated workflow if embargo selected 

### ISSUE THREAD

**Issue by lfarrell** [samvera/hyrax#3817]
When a user deposits a work in a mediated workflow that requires approval and selects embargo the work isn't visible to the depositor until the work is approved. Instead they receive an "Unauthorized" message

<img width="550" alt="Screen Shot 2019-06-06 at 3 52 54 PM" src="https://user-images.githubusercontent.com/436691/59062176-3a2aa280-8873-11e9-9b94-26fc79747f03.png">

**Comment by blancoj** [comment]
@lfarrell I tried to reproduce this on my local machine and on nurax and I could  not reproduce this error.

**Comment by rjkati** [comment]
I was able to replicate in Firefox on nurax-dev using the following steps:

1. Log in as a regular user (not an admin or manager of Admin set 2)
2. Create a work in Admin set 2: mediated deposit and set an embargo
3. Click Save
4. Navigate away from work
5. Click work in "My Works" on dashboard.
6. Observe "Pending Review" page with message "The work is not currently available because it has not yet completed the approval process".

As a user, I would expect to be able to see my deposited works, regardless of where they are in the approval process.

**Comment by jeremyf** [comment]
My read on this is as follows (with some observations afterwards):

1) The mediated deposit workflow Grants read to the depositor and Deactivates the object: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/.dassie/config/workflows/mediated_deposit_workflow.json#L20-L23

2) A deactivated object move to inactive state:  https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/services/hyrax/workflow/deactivate_object.rb#L11-L15

3) A deactivated object will be suppressed: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/models/concerns/hyrax/suppressible.rb#L12-L19

4) Logic that raises an exception when document is suppressed AND current user can read the object: 
https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/concerns/hyrax/works_controller_behavior.rb#L302-L306

5) Logic that captures the exception from above: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/concerns/hyrax/works_controller_behavior.rb#L23

6) Logic that renders in response to the raised exception: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/concerns/hyrax/works_controller_behavior.rb#L308-L322

7) The text for `I18n.t("hyrax.workflow.unauthorized")` is: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/config/locales/hyrax.en.yml#L1522

8) The spec that asserts the expected behavior: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/spec/controllers/hyrax/generic_works_controller_spec.rb#L14-L30

## Observations

This commit (19925b5c354f7ea244b341e509aa316200450956) and related PR #3148 introduced the logic that I believe to be in effect.

I also do not believe that the embargo state is contributing to the problem.  This is a matter of leaky permissions and multiple permission paradigms that are in a non-reconciled.

Given that we have specs asserting the current behavior, this is a much larger question and problem.

**Comment by jlhardes** [comment]
Thanks for this documentation @jeremyf! Item 4 in this list isn't making sense to me. If the doc is suppressed but the current user can read the doc, why is access denied to that user? Is there a difference that can be distinguished there between being able to read a doc and being an owner or depositor of a doc if read access needs to be denied?

**Comment by jeremyf** [comment]
I think step 1 highlights that we don't give "special" consideration for depositor; They are a reader.

(Note: Sipity's permissions are robust enough to handle this question, but it's not an attribute on the object because we have a very flat consideration of the object's permissions as they relate to changing state.)

**Comment by jeremyf** [comment]
Synthesizing the expected behavior of #3104 and the expected behavior of #3817 (this issue), I think we need to establish what an unauthorized user is?

Based on the above logic, the depositor is granted read rights at the time of moving to pending review.  However, the suppressed attribute appears to take a higher priority.

I think we need to establish: for the "inactive state" who should be able to see this object?  I suspect this gets real complicated because the Fedora storage accounts for fewer states than the arbitrary Sipity state machine (which itself models who can see what based on the given state of the object).

A proposed solution would be to address the following chunk of code:

https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/controllers/concerns/hyrax/works_controller_behavior.rb#L302-L306

We need to establish the language of why we're raising a `WorkflowAuthorizationException`.  Reading `doc.suppressed? && current_ability.can?(:read, doc)` I'm a bit at a loss to establish a method name for that.  My understanding is that the intention is "cannot view under current restrictions".  But to make that mental gymnastics easier lets focus on "can view under current restrictions" (note we're raising two different exceptions so this could get gnarly).

```ruby
def can_view_under_current_restrictions?(:ability, :doc)
  return ability.can?(:read, doc) unless doc.suppressed?
  # This may be a useful short-circuit given above mentioned  
  # bifurcation of Sipity's permissions vs. Hydra::AccessControls
  # Assumption: You have a read role assigned to the object during the
  # lifecycle of the object's state machine (e.g., workflow)
  return false unless ability.can?(:read, doc)

  # Assumption for the current state, your role has access to at least one
  # action.
  return Hyrax::Workflow::PermissionQuery.scope_permitted_workflow_actions_available_for_current_state(user: ability.user, entity: doc).any?
end
```

Thoughts?

**Comment by no-reply** [comment]
> If the doc is suppressed but the current user can read the doc, why is access denied to that user?

i think the reason for this is that "suppressed"/[`inactive`](https://wiki.lyrasis.org/display/FEDORA36/Fedora+Administrator) means:

> Inactive: the object is only available to repository administrators.

the logic in [(4)](https://github.com/samvera/hyrax/issues/3817#issuecomment-827672366) is reasoning that, since the object ACLs grant read permissions to the user, the reason they don't have access is the `suppressed?` flag/inactive state, and therefore it should raise a workflow related error and pass the `hyrax.workflow.unauthorized` message, rather than a more generic one.

i think the method name for @jeremyf's abstraction is something like `#unreadable_due_to_workflow_status?`.

as far as i can see, this behavior is correct. there are two interpretations from there:

  1. this workflow is trying to use "suppressed" to mean "not publicly discoverable", and that doesn't really work. it should manage the permissions more carefully.
  2. everything is working as designed and the submitting user *should not* have read access until another stage in the review cycle.

i vaguely recall there being some partisans for the second interpretation at some point, but i can't really remember the context. 

---

for my part, i'm strongly committed to avoiding specialized read/write permissions, overriding ACLs. i'd go so far as to say i think it's slightly problematic that we grant this access with `::User#admin?` software overrides rather than granting `:read` and `:edit` to an admin group explicitly via ACL.

broadly speaking, i'd be concerned about any resolution to this issue involving hard-coded overrides to ACL permissions.

**Comment by jlhardes** [comment]
I agree that there shouldn't be any code changes that override the ACL permissions. If what is happening here is using how the ACL has defined access, and it sounds like it is following the ACL, then it does seem to be working as designed. The depositor is a reader but the work is mediated deposit and has to be approved by (or have a response from) an authorized approver who is not the depositor. That means there is no read access for the depositor until there is a response from an authorized approver. Additionally there is an embargo on the work in this case which further restricts who can view the work but once the work is approved or responded to through mediated deposit, the depositor has read access to the work again. That all seems to be true so I don't think there is a bug to fix here. I have mentioned this issue in #4990 for making sure ACLs manage authorization for works and collections.
