### ISSUE TITLE
Alphasort field entries

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#395]
### Descriptive summary

With rdf2 values may come back in different orders. It could be disorienting for users if things jump around on page reload. We should alphasort here https://github.com/projecthydra-labs/hyrax/blob/master/app/renderers/hyrax/renderers/attribute_renderer.rb#L29. and maybe there are other places?

Should this be an option to attribute_to_html?

**Comment by agoslen** [comment]
SMIG has been discussing open issues labeled metadata. We discussed this issue on 6/22:

- SMIG has recently made the recommendation (for #4781) that Creator, Contributor, and Title are the multi-value fields where ordering would matter most; but this order would be context-dependent, rather than purely alphabetical.
- Would it be desirable for alphasort to be a fallback for field ordering, where user-supplied order is not possible? 
  - No; group consensus is that alphasort is not necessarily better than the out-of-the-box chaos of RDF nonsorting. 
  - Alphasort implies an order and context that is artificial. If this is desirable to a local instance, it could be done locally.

**Comment by no-reply** [comment]
thanks @agoslen. i think on this basis we should close this ticket out and subsume further discussion into #4781.

speaking to the original suggestion: https://github.com/samvera/hyrax/pull/5010 provides a very simple implementation of a `:sort` option for `attributes_to_html`
