### ISSUE TITLE
Safari does not have popup validation on embargo date

### ISSUE THREAD

**Issue by dlim87** [samvera/hyrax#3979]
### Descriptive summary
On other browsers, when trying to submit a work with an invalid embargo date (beyond what is allowed by the admin set), there is a popup which indicates what the maximum value is. On mac safari, this popup doesn't appear, and instead it submits the work but fails with the error `Embargo release date Release date specified does not match permission template release requirements for selected AdminSet.`

It does work fine on iOS safari.

The popup on other platforms:

 ![Image 2019-09-12 at 12 53 02 PM](https://user-images.githubusercontent.com/5492162/64818082-18bb1000-d560-11e9-923c-ff79803d5678.png)

Tested on Mac Chrome 76.0.3809.132 and Safari 12.1.2
<details><summary>hyrax info</summary>
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 48ed925940130bcc5e75092c974555f4f1654390

Nurax Version
ENV: production
SHA: 40b47b0d71af1b958e016ebe49212c1740683133
Branch: 2019-09-12-10-00
Updated: 12 Sep 2019 15:00:37</details>

### Rationale
It is always good to have a consistent UX. This behavior hits the nasty bug with failed submissions (in the related work links)

### Expected behavior
The date would be validated like in other platforms

### Actual behavior
The form submits the invalid date, and then clears all the fields when the submission is rejected

### Steps to reproduce the behavior

0. Open nurax in safari on a mac 
1. Log in
2. Create a new work
3. Go to the relationships tab and select an admin set with an upper bounds for the embargo date (e.g. admin set test 7)
4. Select embargo from the visibility pane, and set the date to something past the upper bounds set by the admin set (e.g. something in 2051)
5. Click on the save button

### Related work

Wouldn't be an issue if this is solved: https://github.com/samvera/hyrax/issues/3978

**Comment by no-reply** [comment]
it seems like this might be a limitation of support for HTML5 form validation in Safari? 

the form input type and min/max are to spec. anyone have ideas about potential work-arounds?

**Comment by no-reply** [comment]
@dlim87 should `Open nurax in chrome on a mac` be `Open nurax in Safari on a mac`?

**Comment by dlim87** [comment]
Oops, yes. Sorry

**Comment by dlim87** [comment]
This has a similar behavior on the edit page. There is no pop-up validation, just the alert box that your embargo date was invalid. Instead of resetting the fields to blank, it reverts them back to the saved data

**Comment by Dananji** [comment]
@no-reply,
The first approach was to swap out the the `date_field` tag to `date_select` tag, which would show up in Safari as a date picker. And this needs changing the model (as I understood), because date passed from the view is 3 separate variables for month, day, and year. But the issue of popup not showing up in Safari will still be an issue. 
The second approach was to do form validation for visibility in JavaScript side of things and show a validation message. This validation message shows up only when the HTML5 validation doesn't work in the browser.
Right now I'm working on the second approach.

**Comment by no-reply** [comment]
@Dananji it seems like JavaScript validation may be too heavy handed, here. HTML5 provides this functionality, and Safari supports it, at least in theory.

Do we have a diagnosis on why this isn't working in Safari?

My working hypothesis is that it's because we change the form details after the page loads (by selecting an admin set). I'm not sure that's the reason, but I think it would be wise to find the source of the problem before introducing new code we'll have to maintain.

**Comment by Dananji** [comment]
Sorry, all this time I was looking for a solution, instead of finding out what's actually causing this :\
Yes I agree. Let me do a little digging and try to find out what's causing this :+1:

**Comment by Dananji** [comment]
When the form is submitted in Safari with an embargo release date > allowed maximum embargo period by the admin set, the server returns `422 Unprocessable Entity`. This means the server cannot process the content in the request even though it understands it.

My guess is that, because Safari doesn't support `input[type="date"]` the form value passed on is not in the format the server expects (server expects a `Date` type while Safari passes on a text value)?

**Comment by Dananji** [comment]
Because Safari does not support `input[type="date"]` the max/min attributes of the input-date field are not recognized by Safari. Therefore the form validation does not happen, which results in the absence of the validation popup.

**Comment by no-reply** [comment]
Closing this as an external browser issue. 

The related #3978 is prioritized as a mechanism for mitigating the form input loss in error cases.
