### ISSUE TITLE
Closely Review README for 3.0.0

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#3998]
Review the README.md in preparation for 3.0.0.

cc: @samvera/hyrax 

it would be good to get review from folks with varying expertise.

**Comment by downwriter** [comment]
https://github.com/samvera/hyrax#what-is-hyrax: It might be good to have link to [Rails Engine](https://github.com/samvera/hyrax#what-is-hyrax).

**Comment by downwriter** [comment]
https://github.com/samvera/hyrax#derivatives

It might be good idea to explain configuration for libreoffice_path (i.e. soffice) in the `config/initializers/hyrax.rb` like is explained in the Transcoding section for ffmpeg

**Comment by downwriter** [comment]
@no-reply wondering about https://github.com/samvera/hyrax/issues/3886 and relation to README.

**Comment by downwriter** [comment]
https://github.com/samvera/hyrax#javascript-runtime 

Since there are links to other software/dependencies like Redis, RVM, Rbenv, etc.; it might be good to have a link to [NodeJs](https://nodejs.org/en/)

**Comment by downwriter** [comment]
https://github.com/samvera/hyrax#generate-a-work-type

Create Default Admin Set shows `bin/rails...` while Generate Work Type shows `rails ...` 

Might not matter on to most people, but the difference could cause trouble for some?

**Comment by downwriter** [comment]
https://github.com/samvera/hyrax#contributing

[Waffle board](https://waffle.io/samvera/hyrax) broken

This might need to be updated to coincide with move away from Waffle? 

```
If you'd like to help the development effort and you're not sure where to get started, you can always grab a ticket in the "Ready" column from our Waffle board. There are other ways to help, too.
```

**Comment by brianmcbride** [comment]
Suggested Updates

[What is Hyrax?](https://github.com/samvera/hyrax/blob/master/README.md#what-is-hyrax)
  - What is Hyrax Section - update the link for Samvera to https://samvera.org/

- [Prerequisites section](https://github.com/samvera/hyrax/blob/master/README.md#prerequisites)
  - Solr version has been tested up to 7.7.2?
  - FITS section - consider moving up the minimum version? v.1.0.1 is over three years old

- [Characterization](https://github.com/samvera/hyrax/blob/master/README.md#characterization) 
  - Update `http://projects.iq.harvard.edu/fits/downloads` link to point to github page? `https://github.com/harvard-lts/fits/releases`

- [Redis](https://github.com/samvera/hyrax/blob/master/README.md#redis)
  - Update `http://redis.io/` link to point to `https://redis.io/`
  - Update `http://redis.io/documentation` link to point to `https://redis.io/documentation`

- [Enable notifications](https://github.com/samvera/hyrax/blob/master/README.md#enable-notifications)
  - update text regarding Hyrax 2 reference.

**Comment by jlhardes** [comment]
Status graphics at the very top:

Code: dependcyci badge image not loading (https://dependencyci.com/github/samvera/hyrax/badge)

Jump in: Waffle badge and link not working, because Waffle is no more - (https://badge.waffle.io/samvera/hyrax.png?label=ready&milestone=2.x%20series&title=Ready )

[What is Hyrax?](https://github.com/samvera/hyrax#what-is-hyrax)
Connect over to About Hyrax for more info (For more information on the history leading up to Hyrax, see https://hyrax.samvera.org/about/). The Sufia/CurationConcerns sentence at the end seems like a long stretch into history and the About page on the Hyrax site offers more info about that if people want to know.

[Help](https://github.com/samvera/hyrax#help)
Is the support guide link supposed to be a .MD or should it point to the Samvera Community Knowledge Base or the Hyrax Management Guide? One of those was what I was expecting and the MD only talks about reporting an issue and contacting the community via Slack and email list. If the KB or the Hyrax Management Guide isn't the link for the support guide then they should be added to the support.md.

[Redis](https://github.com/samvera/hyrax#redis)
"prevent race conditions as a global mutex" - That required some Googling on my part. Can this be explained more plainly, like maybe "Redis is a key-value store that Hyrax uses to provide activity streams on repository objects and users, and helps when modifying order-persisting objects by managing multi-threaded actions on data (preventing race conditions as a global mutex)."

[Generate a Work Type](https://github.com/samvera/hyrax#generate-a-work-type)
Typo (extra words "in the") - Change "If your applications requires your work type to be namespaced, namespaces can be included in the by adding a slash to the model name which creates a new class called MovingImage within the My namespace:"

to 

"If your applications requires your work type to be namespaced, namespaces can be included by adding a slash to the model name which creates a new class called MovingImage within the My namespace:"

[License](https://github.com/samvera/hyrax#license)
Apache 2.0 license link broken - think it should be https://github.com/samvera/hyrax/blob/master/LICENSE

[Contributing](https://github.com/samvera/hyrax#contributing)
Waffle Board no longer exists - need to update (already reported)

**Comment by downwriter** [comment]
`https://raw.githubusercontent.com/samvera/hyrax/v3.0.0.pre.rc1/template.rb` 

```
rails _5.2.3_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v3.0.0.pre.rc1/template.rb
```
I am getting a 404 on this.

**Comment by maxkadel** [comment]
- Structure of ToC - could be clearer. 
  - Make sure all ToC links work (currently they don’t)
  - Getting started - Quickstart in ToC link doesn’t work
  - What is Hyrax? - Feature list link doesn’t work
  - Read ToC on its own and see whether it makes sense as a set of user stories - “As an experienced developer, I want to contribute to the Hyrax rails engine” ; or “As a librarian with good computer skills, I want to test drive installing this application I’m interested in for my institution” (e.g., may need to give a brief “what is a rails engine” explainer or link)
- Generally double check header levels - e.g. why is Characterization 3rd level and Redis 2nd level?  
- I might start the “What is Hyrax” section with the first section from here - https://hyrax.samvera.org/about/managers/
- Prerequisites
  - Make it clear that in order to run in development mode you do not need an independently running Solr or Fedora instance - either put the note before the prerequisites, or after each in the list
  - FITS - note on version seems pretty out of date
  - I’d put Ruby & Rails before the more Hyrax-specific prerequisites
  - Redis - “prevent race conditions as a global mutex when modifying order-persisting objects” - very unclear and jargon-y to me, at a very different level than other portions of README
- Creating a new hyrax application
  - The filename in the command includes “pre”, but the actually hyrax gem version is v3.0.0.rc1 - rails _5.2.3_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v3.0.0.pre.rc1/template.rb
  - Have had to re-run `bundle install` after the template any time I have tried this
- Contributing - “waffle board” is a dead link

**Comment by no-reply** [comment]
@maxkadel thank you!

**Comment by jlhardes** [comment]
Some of the updates listed here were still needed so this pull request is for the suggested edits that are still relevant since the README rewrite/restructure at Dev Congress.
