### ISSUE TITLE
Deprecate FileSetsController#create

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#420]
The UI in Hyrax doesn't call this anymore, as far as I can tell.

**Comment by no-reply** [comment]
If we are deprecating this, we should do it sooner rather than later.

**Comment by RudyOnRails** [comment]
We are scheduled to build an API endpoint here where our imaging department's order management software can send a request with an asset/work uuid and some params, and add a new file_set to a work. I plan to utilize `CurationConcerns::FileSetsControllerBehavior#create`. But, when we migrate from Sufia 7.2 to Hyrax 2.1 in the fall, would there be something else I could use since this ticket will most likely be completed?

Ah crud, it's already done: https://github.com/samvera/hyrax/commit/a4b7c8eb0d22583d003a8fa1d2422a8669dbd715#diff-f4e3b432213aa3b40fa2bd3be564f63e

**Comment by RudyOnRails** [comment]
@no-reply as mentioned above it's already done here: https://github.com/samvera/hyrax/commit/a4b7c8eb0d22583d003a8fa1d2422a8669dbd715#diff-f4e3b432213aa3b40fa2bd3be564f63e

closing.
