### ISSUE TITLE
Hyrax 2.6 pinned to an old version of ActiveFedora. Should it be updated?

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#4232]
### Descriptive summary

Currently, Hyrax 2.6 is pinned to an extremely outdated version of Active Fedora (in this case version 11.5.x ) which still depends on Solrizer. This is old news. We would like to get off of using deprecated methods of interacting with Solr. 

I would like to explore the possibility of updating active fedora to a newer version that doesn't use Solrizer, something like 13.0 if possible, but 12.0 would be fine too since that is when the changes from PR #1223 were released. 

I'm not sure how releasing a new cut for Hyrax 2.x aligns with the release of 3.0. 

If someone could give insight on timing and if it would be possible to do that, I could go forward with trying to bump ActiveFedora to either 13.0 or 12.0.

@no-reply ?

**Comment by no-reply** [comment]
@straleyb i think it's pinned explicitly because Solrizer is removed in AF 12/13.

removing solrizer would be a huge breaking change for Hyrax itself, and adopters. there are certainly ways we could shim in compatibility at the Hyrax level, but unless someone is willing to take on that work, this is necessarily a 3.0 issue.

**Comment by straleyb** [comment]
Heh ok. Thanks for the information. ill update tickets locally about the situation and ill comment the code that we will need to update once we are actually going live on 3.0.0.
