### ISSUE TITLE
Adding a new version of a file does not work until browser cache is refreshed

### ISSUE THREAD

**Issue by njaffer** [samvera/hyrax#4274]
### Descriptive summary
When a depositor or an admin wants to add a new version of a file, they download the file, edits it and upload it back as a new version. After uploading the new version, they download to check it and it downloads the old version. The depositor needs to clear the browser cache and then download it again. This time the new file is downloaded.

This does not happen, if the depositor/admin does not download the file first.

### Rationale

The depositor/admin thinks the new file is not uploaded if they are not aware of the caching issue. This creates confusion among the editors of the file.

### Expected behavior
When the new file is uploaded, the download button should download the new file and not the cached file.

### Actual behavior
The cached file is downloaded instead of updated uploaded file

### Steps to reproduce the behavior
checked on Chrome and Firefox

1. Download a txt file attached to a work
2. Edit it
3. Go to the Version option for the files, upload the new version
4. Check the new version is uploaded in the version history
5. Click on Download this file button, and it downloads the previous version of the file and not newly uploaded version

6. Clear the browser cache
7. Download it again, and this time you will see the updated version of the file

**Comment by no-reply** [comment]
@blancoj i'm noticing that we *do* return `Last-Modified` headers from the downloads controller. in theory, this should be enough for a browser to handle cache control appropriately, since we should be supporting conditional requests from there.

the first thing to check is that those headers do actually update when the file updates. do the browsers tested here actually send `If-Modified-Since` headers for the conditional request?
