### ISSUE TITLE
Add alternative_title to the form

### ISSUE THREAD

**Issue by noraegloff** [samvera/hyrax#4286]
**Descriptive summary**
Alternative_title appears in [basic_metadata.rb](https://github.com/samvera/hyrax/blob/2.5.1/app/models/concerns/hyrax/basic_metadata.rb#L9) but does not appear in the form when editing or creating a Work in Nurax, which is running Hyrax Version: 3.0.0.pre.rc1. 

**Rationale**
Title property has been limited to showing only a single title in the form (see [issue 3299](https://github.com/samvera/hyrax/issues/3299)), and Alternative Title has been added as a field for putting additional title values, but it still needs to be added to the form.

**Comment by no-reply** [comment]
cc: @samvera/hyrax-repo-managers is this something we want to add to the form by default?

**Comment by mark-dce** [comment]
I'd be strongly in favor of having all user supplied metadata expressed in [basic_metadata.rb] listed on the edit form and displayed on the single item show view.  

I think it adds a layer of complexity to have to explain "the fields is present in the model, but you'd have to add code locally if you wanted to be able to edit and display the field in your repository."

**Comment by noraegloff** [comment]
I agree with mark-dce. It's worth mentioning here that Bibliographic_citation has also been added to [basic_metadata.rb](https://github.com/samvera/hyrax/blob/2.5.1/app/models/concerns/hyrax/basic_metadata.rb#L37) but does not yet appear in the form, either.

**Comment by mcdowney** [comment]
No real objection from repo managers, and Mark's point also makes sense to me.

**Comment by svogtunh** [comment]
I am going to weigh in on this.  I also agree with mark-dce that 'all user supplied metadata expressed in [basic_metadata.rb] listed on the edit form and displayed on the single item show view.'  The fix for issue #3299 was treated as alternative_title, but has nothing to do with the alternative_title metadata field, and needs to have its name changed to something like 'title_overflow' so that alternative_title can be added to the form similar to the other metadata fields.

**Comment by agoslen** [comment]
This issue appears to be mostly resolved.

I was able to add two alternative titles to this test work using the form:
https://nurax-dev.curationexperts.com/concern/generic_works/jm214p395?locale=en

and confirm that they are using the http://purl.org/dc/terms/alternative predicate. 

However, the alternative titles do not display on the item view.

As the primary requirement of this issue seems to be making it available on the form, should this issue be closed and another created for item view display?

**Comment by rjkati** [comment]
@jlhardes, per @agoslen's comment, this issue seems to be resolved except for the item view display.

**Comment by jlhardes** [comment]
Created #5015 for displaying alternative titles in item view. Closing this issue.
