### ISSUE TITLE
Edit Admin Set - on smaller viewports, screen scrolls down on save, etc.

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#461]
As a user on a laptop who is editing the participants, release and visibility or workflow of an Admin Set, and when I click on a button to commit a change (save, remove or add), a flash message appears at the top of the screen as expected, but then the browser window scrolls down such that everything above the main panel (tabs, page header, breadcrumbs, flash message) is obscured. 

I would expect the page to load without any scrolling, so that I can see the page in its entirety.

**Comment by laritakr** [comment]
This browser behavior is happening because of the use of anchors in the tabs. When the rerouting happens in the permission_template_controller, it redirects to a particular anchor to display the partial, which automatically scrolls to that anchor for small page sizes. 

https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/hyrax/admin/permission_templates_controller.rb#L13-L25

https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/admin/admin_sets/_form.html.erb#L2-L17

Changing this will apparently require coming up with a way to override the normal browser behavior via javascript.

**Comment by jcoyne** [comment]
@hannahfrost is this still a problem for you? I can't duplicate it.

**Comment by julesies** [comment]
Tested and seems to be working okay now. Closing.
