### ISSUE TITLE
Remove generated feature tests for AF based work types

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5248]
### Current Challenge

The feature spec generated when a new work type is generated using `rails generate hyrax:work GenericWork` fails out of the box.  I've tried several things to get the test to work by comparing the Hyrax feature spec `spec/features/create_work_spec.rb` to the generated spec for the new work type without success.

### Proposed Modification

I would like to propose that we not generate the feature tests.  These seem well tested by Hyrax's feature tests.  It seems like applications should be able to trust that the Hyrax feature testing process is sufficient unless they make extensive customizations.  In that case, the generated feature test would also need extensive modifications to test the customizations. 

Looking for others opinions on this.

**Comment by no-reply** [comment]
it seems fine to remove this. i have a recollection of this test failing out of the box in Hydra/Samvera Camp sessions as far back as 2015/16.

as a matter of principle, i don't agree that applications shouldn't test core features. in this case, the feature in question depends directly on application-owned code (the generated model) and can easily regress due to common errors application side. this point seems academic if we can't ship a feature spec that consistently passes, though, so i'm in favor of just axing it.
