### ISSUE TITLE
Work view page - Items Actions menu not working : ArgumentError in Hyrax::FileSetsController#edit

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5575]
### Descriptive summary

The actions menu on work view page is not working. Click Edit or Versions in drop-down menu gives rise to FileSetsController related errors.

### Steps to reproduce the behavior

1. Log in to user dashboard, then list works, click a work name to display work view page.
2. In the section of "Items", find the dropdown menu "Select an action" and select either Edit or Version from the drop-down menu and click.
3. You will see an error like ArgumentError in Hyrax::FileSetsController#edit

### Related work

#5136 (epic with history of previous work and testing of Works)
#5794 Issue for Download option in Items Actions menu
#5795 Issue for Delete option in Items Actions menu

**Comment by fritzfreiheit** [comment]
app/presenters/hyrax/version_list_presenter.rb

Updated:
```
    ##
    # @param [Object] an object representing the File Set
    #
    # @return [Enumerable<Hyrax::VersionPresenter>] an enumerable of presenters
    #   for the relevant file versions.
    #
    # @raise [ArgumentError] if we can't build an enu
    def self.for(file_set:)
      return new(file_set.original_file&.versions&.all.to_a) if file_set.respond_to? :original_file
      original_file = Hyrax.query_service.find_by(id: Valkyrie::ID.new(file_set.original_file_id))
      new(original_file&.versions&.all.to_a)
    rescue Valkyrie::Persistence::ObjectNotFoundError
      new([])
    rescue NoMethodError
      raise ArgumentError
    end
```

app/models/hyrax/file_set.rb

Added:
```
    # Cast to a SolrDocument by querying from Solr
    def to_presenter
      Blacklight::SearchService.new(config: CatalogController.blacklight_config).fetch(id).last
    end
```

app/views/hyrax/file_sets/_permission_form.html.erb

Modified to get around issue with missing .permissions method (but I assume it shouldn't be missing, which is where I left off)

Modified:
```
<% public_perm = true if params[:controller] == 'batch' %>
<% public_perm ||= f.object.permissions.map { |perm| perm.access if perm.agent_name == "public"}.compact.first if f.object.respond_to? :permissions %>
<% public_perm ||= false %>
```

**Comment by marrus-sh** [comment]
#5878 & #5886 fixed the version presenter stuff and #5889 & #5895 fixed most of the remaining errors here. I’m hoping #5894 solves the last of the problems, but I’m running into the same behaviour as in #5796 now so can’t fully test it.

**Comment by alishaevn** [comment]
I worked on #6085 with @sephirothkod but each of the spec pipelines had dozens or hundreds of failed specs for seemingly unrelated reasons. I tried to resolve some, then went searching in the hyrax-valkyrie slack channel.

turns out that #5877 was created to fix this issue. it was closed in favor of #5987, which is still open. I tested the downloads feature on that branch and it works.... 😥 

closing #6085 in favor of #5987 because it has much fewer failing specs.

editing the file set still doesn't work however, so I'll continue working on that.

**Comment by alishaevn** [comment]
> edit: I was directed to the "descriptions" tab on the edit screen. trying to change the title resulted in an error message: "There was a problem processing your request."

@dlpierce @no-reply 
the problem (seen below) is that the validations are for some reason expecting the license field to be filled in in koppie. it's empty in hyrax as well however, but the edit doesn't fail there. I assume that the desired behavior is that we do **not** want an empty license field to throw an error in koppie. is that correct?

<details>
<summary>hyrax file set</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/d8442061-5476-4eb2-a227-4c9bf8a8b650)
</details>

<details>
<summary>koppie file set</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/4417b453-2089-4bc0-a766-aec79fd89b5c)
</details>

![image](https://github.com/samvera/hyrax/assets/29032869/1ec5ede8-5915-4941-9cf0-95fc842a319d)

**Comment by alishaevn** [comment]
`license` is a [required field](https://github.com/samvera/hyrax/blob/main/app/forms/hyrax/forms/file_set_edit_form.rb#L9) on the file set edit form. however, that form also says `self.model_class = ::FileSet`. that's true for hyrax, but the model class for koppie files is `Hyrax::FileSet`. perhaps that's the reason for the discrepancy?

<details>
<summary>hyrax file set class</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/211f1733-2129-4f77-a925-41aa481f6858)
</details>

<details>
<summary>koppie file set class</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/2e970e76-14fe-4fdf-8a5c-654526aa154e)
</details>

**Comment by alishaevn** [comment]
I commented out requiring `license` in [file_set_metadata.yaml](https://github.com/samvera/hyrax/blob/main/config/metadata/file_set_metadata.yaml#L19) and that didn't work.

next I tracked the what happened when rendering the edit page in hyrax and in koppie. both of them go through the same files. [Hyrax::FileSet](https://github.com/samvera/hyrax/blob/main/app/models/hyrax/file_set.rb) >> [Hyrax::Forms::FileSetEditForm](https://github.com/samvera/hyrax/blob/main/app/forms/hyrax/forms/file_set_edit_form.rb) >> [Hyrax::Forms::FileSetForm](https://github.com/samvera/hyrax/blob/main/app/forms/hyrax/forms/file_set_form.rb). 

still trying to figure out where the difference is since they're both using `:file_set_metadata` and the requirement in that file appears to be getting overlooked.

**Comment by alishaevn** [comment]
removing `license` from being required in [file_set_metadata.yaml](https://github.com/samvera/hyrax/blob/main/config/metadata/file_set_metadata.yaml#L19) and [Hyrax::Forms::FileSetForm](https://github.com/samvera/hyrax/blob/main/app/forms/hyrax/forms/file_set_form.rb) didn't make a difference either. turns out that the `change_set.validate(attributes)` was a red herring. 

the actual problem was in the next line. `transactions['change_set.apply'].call(change_set)` returned the actual error. the exact line that threw the error was in [Hyrax::Transactions::Steps::Save#call](https://github.com/samvera/hyrax/blob/main/lib/hyrax/transactions/steps/save.rb#L35). it was mad because `representative_id=` didn't exist.

![image](https://github.com/samvera/hyrax/assets/29032869/a8538e64-7ba0-4e95-8db4-260f7dafab60)
