### ISSUE TITLE
Collection Type settings should not be editable once created

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5645]
### Descriptive summary

On nurax-dev, 3.4.1, a Collection Type can have its settings edited after it has been created, even though the form guidance indicates this is not possible, and this is undesirable behavior. 

### Rationale

Collection Types settings, such as Branding, Sharing, Multiple Membership or Discovery should not be editable once they are changed. Collection Types are explicitly configured with certain behaviors that should not change once they are established.

### Expected behavior

Once a Collection Type has been created, users should not be able to make changes to the Settings tab, and the checkboxes should be grayed out.

<img width="712" alt="Screen Shot 2022-05-18 at 11 06 30 AM" src="https://user-images.githubusercontent.com/13855987/169077054-e6215ba4-6aac-4bc2-a91a-9db09e9603b4.png">

### Actual behavior

Users can edit and save changes on the Settings tab.

<img width="764" alt="Screen Shot 2022-05-18 at 11 04 03 AM" src="https://user-images.githubusercontent.com/13855987/169077152-b95a8647-a0ed-4776-aa7e-315a88c54f92.png">

### Steps to reproduce the behavior

1. Login as an admin user on nurax-dev or an instance running 3.4.1 with multiple Collection Types created
2. Go to Settings > Collection Types
3. Edit an existing Collection Type e.g. [Single Membership](https://nurax-dev.curationexperts.com/admin/collection_types/11/edit?locale=en#settings)
4. Go to the Settings tab, and select or deselect the option checkboxes.
5. Save the changes.
6. Go back to Collection Types, and edit the same Collection Type 
7. Open the Settings tab and see that the changes have persisted.

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
@jlhardes FYI this is not directly related to Blacklight 7 work, but seems to be a bug in 3.4.1.

**Comment by jlhardes** [comment]
I think this is working as it should on nurax-dev and `bl7bootstrap4` but this should be verified before this issue is closed.

From what I can see, Collection Types that are created can have changes made on the Settings tab checkbox list until a collection is created of that type. At that point the checkbox list on the Settings tab is disabled. So the steps to reproduce this should include creating a collection using that collection type and then trying to edit the Collection Type again. At that point the checkbox list should be fully disabled. 

On nurax-dev and on my local build of `bl7bootstrap4`, that is how things are working from my testing but can you verify @eporter23? 

The interface issues that were reported in #5631 are still issues in `bl7bootstrap4` but I think this particular issue might not be a problem?

**Comment by eporter23** [comment]
Thank you @jlhardes, that's a relief! I think since some of the data has been purged on nurax-dev, that is why I assumed this wasn't functioning since we use the Single Membership type for testing so often. I have confirmed the behavior as you described both on nurd-dev and on the  bl7bootstrap4 branch.
