### ISSUE TITLE
AdminSets can not be created in Hyrax if config.enable_noids = false

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#5788]
### Descriptive summary
AdminSets can not be created in Hyrax if `config.enable_noids = false`

Tested in v3.4.1 but appears to exist in current code as well. 

### Actual behavior
Admin Set creation fails during after save callbacks at [set_owner_attributes in ActiveFedora](https://github.com/samvera/active_fedora/blob/v13.2.7/lib/active_fedora/associations/has_many_association.rb#L30). Result is an admin set which has no permission template. 

The solr query in collection_association.rb returns `-isPartOf_ssim:[* TO *]` because [construct_query expects an id on the unsaved AdminSet.](https://github.com/samvera/active_fedora/blob/main/lib/active_fedora/associations/collection_association.rb#L295).

In Hyrax, the [model transformer assumes you either have or mint an id](https://github.com/samvera/hyrax/blob/main/lib/wings/model_transformer.rb#L112-L116).

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
i think the code you're concerned about in the model transformer was first introduced in 2019, and has been in every release since 2.5 https://github.com/samvera/hyrax/commit/f2c66bbc581e77c46e9c83103d2e7c33f04fba50.

----

my read is that this issue was introduced somewhere around here: https://github.com/samvera/hyrax/commit/f000b8b2dc179747fef066a111b112953f8a5599

**Comment by orangewolf** [comment]
Back port for 3.x and patch for 4.x are both merged. This is resolved.
