### ISSUE TITLE
Unable to delete collections in valkyrie/fedora

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6362]
### Descriptive summary

When I attempt to delete a collection using sirenia, I receive a "NoMethodError in Hyrax::Dashboard::Collections#destroy" message

### Steps to reproduce the behavior in User Interface (UI)

Pre-req: create a collection or have manager access to a collection

1. In valkyrie/fedora (sirenia), log in and navigate to Dashboard -> Collections
2. Click on the title of a collection
3. Click "Delete Collection"
4. Click "OK"
5. Observe error message

### Actual behavior (include screenshots if available)

Attempting to delete a collection returns a "NoMethodError in Hyrax::Dashboard::Collections#destroy" message

![collections-delete](https://github.com/samvera/hyrax/assets/32644254/84f9298e-1c81-4dde-8aae-5fe0355d82b4)

### Acceptance Criteria/Expected Behavior

Clicking "Delete Collection" should delete the collection without an error.

**Comment by bwatson78** [comment]
This is caused by [the collection member cleanup listener](https://github.com/samvera/hyrax/blob/6dfac421ccce905ccd8bbc593161dd9e034d09f4/app/services/hyrax/listeners/member_cleanup_listener.rb#L29) querying a "tombstone"'d (deleted) Fedora object (much like the Koppie issue of orphaned FileSet and related ACs and FMs; see [here](https://samvera.slack.com/archives/CDRHAMUTV/p1697469137578709)). I will pass along the members before the collection is deleted.
