### ISSUE TITLE
One step mediated deposit: 'approving' role notifies 'approving' role on 'request_changes' action?

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#935]
This seems weird. Is it the desired behavior?

https://github.com/projecthydra-labs/hyrax/blob/ff36af31619e9b18190208cc4aa2f3c5583ed7dd/lib/generators/hyrax/templates/mediated_deposit_workflow.json.erb#L24-L32

**Comment by mjgiarlo** [comment]
@hackmastera I'm guessing that should be `depositing` instead. Good catch.

**Comment by jcoyne** [comment]
I think this doesn't have a functional implication because it's hard coded to use the depositor here: https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/workflow/changes_required_notification.rb#L17.  @jeremyf can you take a look and recommend a course of action?

**Comment by laritakr** [comment]
My testing confirmed that all reviewers are getting notified of approvals, in addition to the depositor.

**Comment by rjkati** [comment]
When I submit a work to an admin set with a one-step workflow, both approver and depositor accounts receive the same message: "[work name] ([work number]) was deposited by [depositor] and is awaiting approval"

When the approver account requests changes to the work, both approver and depositor accounts receive the same message: "[work name] ([work number]) requires additional changes before approval. ''

Is this the expected behavior? @jlhardes

**Comment by jlhardes** [comment]
What @rjkati is describing makes sense for the messages received by the depositor and approver for both of those actions. The second message lets the approver know that the request for changes is in place just like the first message lets the depositor know that the work has been deposited and is ready for approval. Is there something about the process or something in the code that still seems not quite right, @hackartisan, or can this be closed?

**Comment by hackartisan** [comment]
If it works for y'all I'm happy for the issue to be closed!
