### ISSUE TITLE
Notifications for reviewer role going beyond the admin set

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#936]
### Descriptive summary

Anyone with reviewer role on an admin set is getting the notifications for works submitted on ALL admin sets.
This issue exists in both the 1-0 stable and the master branch.

### Rationale

Users with the approving role should only get useful notifications. 

### Expected behavior

Anyone with the workflow role of reviewer on an admin set should be notified of works submitted to that admin set which they should review.

### Actual behavior

Anyone with the workflow role of reviewer on any admin set are getting notifications of works submitted to all admin sets.

### Steps to reproduce the behavior

I created two separate admin sets and 6 users with varying participant roles and workflow roles, and submitted works from each user who was able to submit to each admin set. Reviewers for only admin set 1 received notifications for works submitted to both admin sets. 

[Spreadsheet of users, roles, and what they were able to do in the app.](https://docs.google.com/spreadsheets/d/1zQsWlYMVs7gz6dHaOiXICygLj_5GTFOmbpI9MHRAq5o/edit#gid=0)

**Comment by jcoyne** [comment]
Possibly returning wrong values here: https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/notification_service.rb#L50

**Comment by darrenleeweber** [comment]
Translating the PermissionQuery. into some SQL, we get
```sql
SELECT CAST("sipity_agents"."proxy_for_id" AS integer)
FROM "sipity_agents"
WHERE (
	"sipity_agents"."id" IN (
		SELECT "sipity_workflow_responsibilities"."agent_id"
		FROM "sipity_workflow_responsibilities"
		WHERE "sipity_workflow_responsibilities"."workflow_role_id" IN (
			SELECT "sipity_workflow_roles"."id"
			FROM "sipity_workflow_roles"
			WHERE "sipity_workflow_roles"."role_id" IN (1)
		)
      ) OR "sipity_agents"."id" IN (
		SELECT "sipity_entity_specific_responsibilities"."agent_id"
		FROM "sipity_entity_specific_responsibilities"
		WHERE "sipity_entity_specific_responsibilities"."workflow_role_id" IN (
			SELECT "sipity_workflow_roles"."id"
			FROM "sipity_workflow_roles"
			WHERE "sipity_workflow_roles"."role_id" IN (1)
		) AND "sipity_entity_specific_responsibilities"."entity_id" = '1'
      )
) AND "sipity_agents"."proxy_for_type" = 'User'
```

**Comment by mjgiarlo** [comment]
@darrenleeweber You're right that this query doesn't involve AdminSets at all. The Sipity internals work independent of AdminSets, and we have yet to reconcile the two models for assigning roles (the [ones defined in Sipity workflows](https://github.com/samvera/hyrax/blob/master/lib/hyrax/role_registry.rb#L7-L29), and the [ones used for AdminSets](https://github.com/samvera/hyrax/blob/master/app/models/hyrax/permission_template_access.rb#L9-L11))

It's complicated further by the fact that the roles defined in the default workflows bundled with Hyrax map cleanly to the AdminSet roles, but downstream users are free to define their own roles that do not map cleanly to AdminSets.

Tagging in @jeremyf and @jcoyne, the two folks who best understand this particular module.

**Comment by darrenleeweber** [comment]
I’ll try to note how I understand the problem, at the moment, for the workflow permission problem (I may condense this chat into the issue later); not sure if this will make sense or not, but here goes:
- notifications can be sent to an `Agent` (aka `User`) with a `Responsibility` (using a preferred notification method)
- Sipity has two types or “levels” of `Responsibility`:  `EntitySpecificResponsibility` and `WorkflowResponsibility`
  - a `WorkflowResponsibility` is independent of any `Entity` in the workflow (and the state of the entity in the workflow)
  - an `EntitySpecificResponsibility` is independent of any type of `Workflow`
- notifications are currently sent to all the `Agent`s who have one or both of these `Responsibility` types

In https://github.com/samvera/hyrax/issues/936, the “expected behavior” is:
`Anyone with the workflow role of reviewer on an admin set should be notified of works submitted to that admin set which they should review.`

**Comment by darrenleeweber** [comment]
Notes on reproduction:

- start the development app
  - run `solr_wrapper` and `fcrepo_wrapper` in separate windows
  - `bundle exec rake engine_cart:server`
- sign-up with an admin user (already added to `.internal_test_app/config/role_map.yml`)
- create a new `Administrative Set`
  - click on `Administrative Sets` in the left side panel
  - give it a name, e.g. "Review Notifications"
  - click the save button
- edit the new admin-set
  - note that the `Workflow` tab has two options, a `default` and a `one-step mediated` workflow
